### ISSUE TITLE
Some Errors Occured: Cannot install an older version of an app

### ISSUE THREAD

**Issue by dominikheinz** [ImranR98/Obtainium#674] opened 2023-07-15 11:22 UTC
**Summary:**

While updating works perfectly fine for most apps, some apps cause problems. 
One of these apps that cause problems is [Waterfly](https://github.com/dreautall/waterfly-iii).
I have version `v0.1.7-beta` installed, and the latest version is `v0.1.8-beta`. However, when I try to install the update, I am prompted with an error: "_Cannot install an older version of an App: [com.dreautall.waterflyiii]_". (See attached Screenshots).
Something makes Obtainium think the version I am trying to install is older than the one that is already installed?
Maybe it has to do with how the version string is evaluated? The app was installed via Obtainiums GitHub search feature.

| Version Overview | Installation Error |
|----------|----------|
| ![signal-2023-07-15-131839_003](https://github.com/ImranR98/Obtainium/assets/32770080/de73aa3b-c073-46d8-aeb1-a963e72e0b0a)  | ![signal-2023-07-15-131839_002](https://github.com/ImranR98/Obtainium/assets/32770080/3c8960b9-b989-4f11-a6a0-0fae82e5d539) |

**Comment by ImranR98** [comment] 2023-07-15 11:43
Try installing the 0.1.8 apk manually just to see if that works

**Comment by ImranR98** [comment] 2023-07-15 11:46
Just tried it myself - the newer version has a lower versioncode so android won't allow you to install it. From the OS point of view, it's an older version - versioncodes should always go up, not down. Newer one is 1083, older is 2096.

**Comment by ImranR98** [comment] 2023-07-15 11:46
Duplicate of #632

**Closed by ImranR98** 2023-07-15 11:46 UTC
