### ISSUE TITLE
Add WhatsApp to sources

### ISSUE THREAD

**Issue by drixdos** [ImranR98/Obtainium#387] opened 2023-03-25 22:12 UTC
Hey, WhatsApp is the only proprietary app that I have on my phone, and I would preferably not use another package management method besides Obtainium just for a single application. 

Could you maybe add WhatsApp to the sources? I think the version on their website is not up to date, but maybe there is another way or the developers could be quickly contacted to keep the versions up to date?

Thanks in advance.

**Comment by ImranR98** [comment] 2023-03-26 00:19
Hey, this is a duplicate of #357. As mentioned there, the version number on their website is out of date, and as far as I know, there's no other official webpage or API endpoint that will give us the version number. If you do, please let me know. 

We can't use an unofficial source as it may not be reliable and may go out of sync.

**Closed by ImranR98** 2023-03-26 00:19 UTC

**Comment by drixdos** [comment] 2023-03-26 02:50
I directly downloaded it from here https://www.apkmirror.com/apk/whatsapp-inc/whatsapp/whatsapp-2-23-7-12-release/whatsapp-messenger-2-23-7-12-android-apk-download/ and then added that as source as well. When I now am on the obtanium app and click remove with the option to deinstall the app as well, I get the message that the app was not found.

What am I doing wrong @ImranR98

**Comment by ImranR98** [comment] 2023-03-26 02:55
That's actually a separate bug. APKMirror is a track-only source, and track-only Apps cannot be downloaded, installed, or uninstalled through Obtainium. So the uninstall option should not be shown - will fix this in the next release.

**Comment by drixdos** [comment] 2023-03-26 02:57
So in the next release I will be able to install and uninstall directly from obtanium?

And for when is that release planned?

Thanks :)

**Comment by ImranR98** [comment] 2023-03-26 03:01
No, we can't install/uninstall track-only apps. The next release will remove the 'uninstall' toggle for these apps so as not to confuse the user.

It will be released when there are a more bugfixes/features ready. A tiny fix like this one isn't worth making a release for.

**Comment by ImranR98** [comment] 2023-03-26 03:03
You can search through the closed issues for "track only" and/or "APKMirror" to know more about why APKMirror apps can't be installed/uninstalled via Obtainium.

**Comment by drixdos** [comment] 2023-03-26 03:05
But the tracking will work properly @ImranR98? So when a new version comes out I will be notified?

**Comment by ImranR98** [comment] 2023-03-26 03:38
Yes, that should already be working fine (I assume you're talking about APKMirror and not the WhatsApp website which is not enabled).
