### ISSUE TITLE
Enhanced Version Detection (continuation of #132)

### ISSUE THREAD

**Issue by S-Sajith** [ImranR98/Obtainium#136] opened 2022-12-05 07:28 UTC
- I'm encountering this bug after updating to v0.8.2 of obtainium , this bug didn't exist before
- This bug seems to happen only when the app version number  has "**.ose**" at the end of the version number
- Updating the app again doesn't fix the issue , removing and re-adding the app to the list also doesn't seem to fix the issue.
- I have attached screenshots below for reference
![Screenshot_20221205-124935](https://user-images.githubusercontent.com/88919814/205577279-8e76937d-38f2-458b-be44-238a646291e0.png)
![Screenshot_20221205-124927](https://user-images.githubusercontent.com/88919814/205577304-32a824ee-b427-4608-ba94-f1020d3cb058.png)
![Screenshot_20221205-124924](https://user-images.githubusercontent.com/88919814/205577348-58b1c9f5-97d9-4062-b100-28d5be112239.png)

**Comment by NathanC** [comment] 2022-12-05 11:56
Same here. For me, it seems to have changed how it parses "v" as part of version string. e.g. it tells me to update from v1.0 to 1.0, even though there's no difference.

**Comment by S7venLights** [comment] 2022-12-05 19:46
I also had a number of apps tell me they need updates after installing Obtaonium 0.8.2 even though they were up to date. But re-downloading them seems to rectify the issue.

**Comment by ImranR98** [comment] 2022-12-05 21:04
This _should_ be fixed in the new release (hopefully, only did minimal testing): https://github.com/ImranR98/Obtainium/releases/tag/v0.8.3-beta

For apps already affected, you'll need to manually mark as updated or re-install. But it shouldn't happen again after that.

**Comment by NathanC** [comment] 2022-12-05 22:27
@ImranR98 the new version does seem to have different version parsing behavior, though it looks like only a subset of the ones I manually updated on the last version (stripping off version info) showed up as needing update after upgrading Obtainium to [v0.8.3-beta](https://github.com/ImranR98/Obtainium/releases/tag/v0.8.3-beta).

Interestingly enough, Obtainium flagged itself as one of the ones needing update after the v0.8.3 update, adding the `-beta` suffix back on.

Mind giving a tl;dr; of what happened here? Seems like just parsing of version strings, but curious for the highlevel of what happened.

**Comment by ImranR98** [comment] 2022-12-05 22:39
Originally this was only meant to work with Apps that followed a "standard" versioning system, like `xx.yy.zz` (see the first few comments). I tried to act smart and add support for other common ones like `-beta`, `-beta05`, etc. and ended up running into these edge cases and bugs. I'm changing some things and will take extra time to test it, hopefully the next release will have all these issues ironed out.

**Comment by ImranR98** [comment] 2022-12-06 01:18
Everything should now work fine with the latest version 0.8.4, but I'm leaving this issue open as the current implementation of version detection only works for a minority of Apps. Will continue trying to extend this support.

**Comment by eloffmarijan** [comment] 2022-12-06 06:01
In the latest update almost everything got fixed, but leaving one behind (in my case).
![Screenshot_20221206-112231](https://user-images.githubusercontent.com/101601874/205831881-ac2472b9-ecb8-47ea-9ef1-25c84c32aaf9.png)

**Comment by NathanC** [comment] 2022-12-06 15:57
In 0.8.4, one of my apps is still consistently broken. It doesn't seem to update at all when I press update— the message goes away for a little while, then comes back and its the same:

![Screenshot](https://user-images.githubusercontent.com/6182419/205958916-a11df108-d7d6-476c-9fe5-70c35d5b7337.png)

This doesn't map to the GitHub version name: https://github.com/AnySoftKeyboard/AnySoftKeyboard/releases

Thanks for triaging this, btw! It's a fairly serious issue, but these things happen, and I appreciate your work on it. Normalizing GitHub release versions sounds like hard problem.

**Comment by S7venLights** [comment] 2022-12-06 19:12
Just wondering, was the change from the old way of, getting version numbers by downloading the APK, necessary?

**Comment by NathanC** [comment] 2022-12-06 19:17
I'd agree with S7ven. It seems like the most reliable system would be version number in APK + date of artifact release on GitHub, segmented by if it's flagged as a per-release. It might save you a lot of headache to just use that, and have the github release title be only on the UI layer. APKs would only need to be downloaded when a new release is cut.

GitHub release versions don't seem to follow a consistent pattern from what I've seen.

**Comment by ImranR98** [comment] 2022-12-08 01:42
Yeah I keep finding weird edge cases, and the detection turns out to be broken in the background process (since the plugin doesn't work) which means update checking might not work right.
So this method has turned out to be a lot less simple/reliable than I thought, and has been completely removed in the latest version: https://github.com/ImranR98/Obtainium/releases/tag/v0.8.6-beta
I'll try coming up with a different approach at some point.

The issue with using release dates instead of versions is that some sources may not provide release dates - versions are the only thing we can reasonably expect to always have access to.

**Comment by NathanC** [comment] 2022-12-08 01:48
I meant the date of the github release itself. e.g., for Wikpedia, they [use a single release channel](https://github.com/wikimedia/apps-android-wikipedia/releases) called "latest" which they update periodically, but it was updated 12 minutes ago and shows that in the browser (and presumably in the API). The date of the last release could be cached locally, and when the release shows a newer date it could be inferred to be a newer release (which could be confirmed by downloading the APK and looking at `versionCode` and `versionName`).

I don't know much about android versioning though, so this may not be useful. Thanks for the quick turnaround on all the recent bug fixes!

**Comment by ImranR98** [comment] 2022-12-08 02:02
Right now, all apps from all sources have the same schema and use the same code for update checking, etc. Customizing these things on a per-source basis could get really messy (GitHub may provide release dates/times in the API, but others may not).

It's also not clear that using dates would fix anything. The original issue is that when an App version changes externally (the user updates something manually or through an app store), these changes are not picked up by Obtainium which only knows about its own internal versions being tracked. We need a way of converting between the "real" version of a given app (seen in the OS settings) to/from the "fake" version tracked internally by Obtainium; right now that internal version is the version string from the source; I'm not sure how switching to a datetime string would help.

**Comment by S7venLights** [comment] 2022-12-08 05:44
People just shouldn't do updates outside of Obtainium if that's what they're using. 😅

**Comment by C8opmBM** [comment] 2022-12-08 15:35
I have all my apps from github, half of them (about 15) show as having updates available.
Need to mark each as having been already updated.
I do not know what broke this functionality, I haven't had this issue a week or so ago.

A fix please, it driving me nuts.
Pixel 6, android 13, latest obtainium.
Thank you!

**Comment by ImranR98** [comment] 2022-12-09 05:24
Trying a simpler approach; seems to work fine at least with the Apps mentioned in this thread, but needs more testing. Would appreciate any testing and feedback:

[app-x86_64-release.zip](https://github.com/ImranR98/Obtainium/files/10192008/app-x86_64-release.zip)
[app-release.zip](https://github.com/ImranR98/Obtainium/files/10192009/app-release.zip)
[app-armeabi-v7a-release.zip](https://github.com/ImranR98/Obtainium/files/10192010/app-armeabi-v7a-release.zip)
[app-arm64-v8a-release.zip](https://github.com/ImranR98/Obtainium/files/10192011/app-arm64-v8a-release.zip)

Note: Remove Obtainium from the Apps list so it doesn't try to downgrade.

**Comment by S7venLights** [comment] 2022-12-09 15:14
No issues with above test version so far

**Comment by ImranR98** [comment] 2022-12-09 15:28
Looks like the above version has issues in the background update checking task. Will look into it later.

**Comment by S7venLights** [comment] 2022-12-09 21:29
Oh yeah, I can confirm I'm probably getting the same behavior

**Comment by ImranR98** [comment] 2022-12-10 04:35
Try this one:

[app-x86_64-release.zip](https://github.com/ImranR98/Obtainium/files/10199179/app-x86_64-release.zip)
[app-release.zip](https://github.com/ImranR98/Obtainium/files/10199180/app-release.zip)
[app-armeabi-v7a-release.zip](https://github.com/ImranR98/Obtainium/files/10199181/app-armeabi-v7a-release.zip)
[app-arm64-v8a-release.zip](https://github.com/ImranR98/Obtainium/files/10199182/app-arm64-v8a-release.zip)

**Comment by S7venLights** [comment] 2022-12-10 09:05
Will test… For now,  I have noticed the 'please wait' after download isn't showing anymore…

**Comment by ImranR98** [comment] 2022-12-11 07:03
https://github.com/ImranR98/Obtainium/releases/tag/v0.8.8-beta

**Closed by ImranR98** 2022-12-11 07:03 UTC
Labels: enhancement, high priority
