### ISSUE TITLE
Better version string extraction for links auto-redirecting to actual apk URLs

### ISSUE THREAD

**Issue by zzColin** [ImranR98/Obtainium#1997] opened 2024-12-01 15:28 UTC
For WeCom official website homepage (https://work.weixin.qq.com/), it is possible to use the custom filter "commdownload\?platform=android" to get the WeCom APK download link, which is always https://work.weixin.qq.com/wework_admin/commdownload?platform=android&from=wwindex. This link will automatically redirect to the actual APK URL, which for now is https://dldir1.qq.com/wework/work_weixin/WeCom_android_4.1.31.32492_arm64_100001.apk. Obviously, the "4.1.31.32492" part is a version string, but I cannot find a way to utilize this. It should be useful if version string extraction will work in this case. This should also be applicable if I add https://work.weixin.qq.com/wework_admin/commdownload?platform=android&from=wwindex directly and override it to "Direct APK Link".

(I know I can get it from Tencent App Store, but only 32-bit APK is available there. The APK from the official website is 64-bit.)

![Screenshot_20241201-232556_Obtainium](https://github.com/user-attachments/assets/d362d586-4d03-47e5-a686-d9a11d394b1f)

**Comment by ImranR98** [comment] 2024-12-01 18:26
Duplicate of #771

**Closed by ImranR98** 2024-12-01 18:26 UTC
Labels: enhancement, to check
