### ISSUE TITLE
Can't add or update Iceraven

### ISSUE THREAD

**Issue by NaeemBolchhi** [ImranR98/Obtainium#623] opened 2023-06-21 02:47 UTC
![Screenshot_20230621-083915_Obtainium](https://github.com/ImranR98/Obtainium/assets/42773187/e5cf4ef1-0e46-4232-bb52-994a762f0ab3)

I'm getting this error when trying to install Iceraven Browser. I tried unintalling the browser first, but same issue. I was able to update the app manually with an apk. For the record, the app id shown by Obtainium for this app is missing the last part. It's incomplete. I wonder if that's what's causing the issue.

**Comment by ImranR98** [comment] 2023-06-21 02:53
Probably a duplicate of #103. Reopen the issue if turning off "infer app id" when adding the app doesn't help.

**Closed by ImranR98** 2023-06-21 02:53 UTC
