### ISSUE TITLE
update doesnt work on Xiaomi 

### ISSUE THREAD

**Issue by skyerjoe** [ImranR98/Obtainium#661] opened 2023-07-12 19:10 UTC
**Phone:** mi9tpro  **isa:**  arm64v8a
**Os**:miui 12.5.1 global based on Android 11

I tried to update obtanium itself but after i choose the default paktetinstaller nothing happens.

Best regards 
John

**Comment by kabigonfanb01** [comment] 2023-07-23 11:21
Phone: redmik40ge isa: arm64v8a
Os:miui 13.0.9 China verson based on Android 12

Same problem as posted however using a different xiaomi phone and os version.  Choosing to update via sellecting update icon on app or update all icon results in apk downloaded into cache but package install is not triggerred so nothing happens.

https://github.com/ImranR98/Obtainium/assets/139830221/992fcf17-bd8e-4277-8659-f012c3876c02

Obtanium is trusted to install unknown apk although it never seems to ask for that permission

**Comment by 2dmnGood4u** [comment] 2023-08-10 12:00
Same experience on Xiaomi device

**Comment by entropy1453** [comment] 2023-08-14 16:48
I also can't update apps on my Xiaomi phone (MIUI 11)

**Comment by skyerjoe** [comment] 2023-08-19 08:51
Update: 

Now with least Update from obtanium itself ( dont know exactly why) everything works, he doesnt show up the packege Installer prompt but everything and all other apps  will be updated in the Background.
 
So my Problem is solved , but i will be nice to see that obtanium is installing sth. due to Security reasons

Thnx for fixing 

Ps: i ll let  the thread Open due to the other Users issues. 

Best regards

**Comment by entropy1453** [comment] 2023-09-10 17:29
**_ImranR98_**, if you can't fix this error, maybe you could add a switch to the settings (e.g. install mode: standard (as it is now, with the installer window hidden) and direct (normal access to the apk file without hiding the window)). This should help, at least as a temporary solution

**Comment by ImranR98** [comment] 2023-11-07 15:42
@tom8zds  OpenFile is an old method that doesn't allow for things like silent installs. I don't think it's worth supporting two separate installation methods (especially since it requires extra permissions) just to support Xiaomi's  messing around with Android APIs.  I didn't realize this before but this issue is a duplicate of #583. The solution is to disable MIUI's "optimizations" to Android: https://github.com/ImranR98/Obtainium/issues/583#issuecomment-1636514808

**Closed by ImranR98** 2023-11-07 15:42 UTC
Labels: bug

**Comment by skyerjoe** [comment] 2024-05-19 10:32
the optimizationd seems not the issue , it works even without deactivating optimizations. 

Best regards
