### ISSUE TITLE
Updating APKs result in "conflict" error

### ISSUE THREAD

**Issue by SleepzCat** [ImranR98/Obtainium#798] opened 2023-08-24 18:21 UTC
When I try and update APKs I get a conflict error. The only apps I have been able to test are Cromite and Kotatsu though as those are the only apps that can be updated for me currently. It's not letting me post the screenshot so here's a catbox link: https://files.catbox.moe/ijz2oo.png

**Comment by ImranR98** [comment] 2023-08-24 19:26
This is likely not an Obtainium issue. Go to `Android/data/dev.imranr.obtainium/cache` in your phone's file browser, and find the Cromite and Kotatsu APKs in there (they should have been cached after you got the error). Then try installing them manually. If it fails, that means the APKs have some conflict with the versions of those apps already on your phone.

Most likely due to something like having installed the app originally from one source (like F-Droid) then trying to update it with an APK from elsewhere (different signing keys).

If the APKs are not in the cache folder, try installing the update through Obtainium again, let it fail, then check the cache folder again. If manually installing the APK does work, try removing the app from Obtainium and re-add it.

**Comment by SleepzCat** [comment] 2023-08-24 23:44
I tried manually installing from the cache (Kotatsu APK) but there was still a conflict. The APK I have installed is directly from github and not through F-Droid, so there should be no conflict. I can't properly test this with Cromite now either as they have released a test build earlier today that doesn't have an android APK and that's what Obtainium is recognizing as the latest build.

**Comment by SleepzCat** [comment] 2023-08-24 23:47
I will say though that I'm 100% certain that the Cromite APK is downloaded from github as I downloaded it earlier this week, and it had this conflict yesterday as well when trying to update it through Obtainium.

**Comment by alphamaestro555** [comment] 2023-08-25 10:35
I can confirm Obtainium does not detect the correct version of Chromite.
Even though release v116.0.5845.111-0747986f1c3f5fd1ad219a23c34a460b6d44aff3 is flagged "latest" Obtainium detect the previous TEST-15 release as latest (that have different signature).

https://github.com/uazo/cromite/releases

Is there a setting in Obtainium to circumvent this?

**Comment by ImranR98** [comment] 2023-08-25 14:29
Obtainium doesn't use the "latest" tag from GitHub because  doing so requires second API call. Instead we look at the release date of the release. Sometimes the release date of the latest tagged release is actually older then some other release, which is the case for Chromite, where TEST-15 was created a few hours later. See #740 for more details. It didn't occur to me before (which is why that issue is marked as won't fix), but there might be a way to work around this by adding a "check 'latest' tag" toggle. This would result in 2 separate API calls but only for a few apps that the user has problems with.

**Comment by SleepzCat** [comment] 2023-08-26 00:19
There was a new release for Cromite and I tried updating it and it worked this time. Not sure why there was a conflict for their last version update, but this one updated fine. Kotatsu still doesn't work, but I tried doing it manually with the APK straight from github and I got a conflict as well. I know for sure it was originally downloaded from github, so I'm wondering if I updated it from F-Droid at some point since then, and that's what's causing the conflict.

**Comment by SleepzCat** [comment] 2023-08-26 00:23
I just deleted Kotatsu, redownloaded the same version from Github again and then updated it through Obtainium and it worked. I must've updated the app through F-Droid at some point and that caused it to result in a conflict error.

**Comment by ImranR98** [comment] 2023-08-26 00:26
Yes, most F-Droid apps use the F-Droid signing key instead of the developer's own key, so F-Droid apps generally dont mix with non-F-Droid ones.

I'm reopening the issue since the problem you faced with Kotatsu has and probably will happen again for other apps - may as well add a toggle to let the user work around it.

**Comment by ImranR98** [comment] 2023-08-26 01:06
Added: https://github.com/ImranR98/Obtainium/releases/tag/v0.14.0-beta

**Closed by ImranR98** 2023-08-26 01:06 UTC
Labels: bug, TODO
