### ISSUE TITLE
SyncThing update failure.  "Null check operator used on a null value"

### ISSUE THREAD

**Issue by DiagonalArg** [ImranR98/Obtainium#1251] opened 2024-01-07 11:34 UTC
Obtainium 0.15.5-beta

SyncThing 1.27.1
https://f-droid.org/packages/com.nutomic.syncthingandroid/

Error on upgrade of SyncThing from 1.27.1 to 1.27.2.1

"Null check operator used on a null value [SyncThing]"

I notice that the version numbers have gone from 1.27.1 to 1.27.1.1 to 1.27.1.2.  At this moment, the latter is "suggested".

**Comment by ImranR98** [comment] 2024-01-07 15:51
Could you try clearing cache?

**Comment by DiagonalArg** [comment] 2024-01-08 01:30
Too late on this one.  I shifted from f-droid to github for the source, and re-installed.  I'll let you know if it happens again, and in that case, reopen.

**Comment by DiagonalArg** [comment] 2024-01-14 11:14
Ok, I'm getting the identical problem with Signal.

Latest version: 6.43.2
Installed Version: 6.42.3

I'm clearing the cache, and ... It works!  :+1:

**Comment by mariobrostech** [comment] 2024-01-31 19:06
I'm experiencing the same problem with the Brave browser now. I have [their GitHub source](https://github.com/brave/brave-browser) added to Obtainium with the following settings changed from their defaults:
- Include prereleases: toggled ON
- Filter Release Titles by Regular Expression: "Release"
- Filter APKs by Regular Expression: "Bravearm64Universal.apk"

I have used this configuration for several months and have only started running into problems with the most recent releases of Obtainium. @ImranR98, I feel like it's appropriate to re-open this issue and investigate what's going on. If there's any logs I can send your way or anything I should do to help debug this, please let me know and I'd be happy to do so. Thanks in advance!

**Comment by ImranR98** [comment] 2024-01-31 19:09
I think I know roughly what the issue is, so I don't think logs are needed. Unless clearing the cache doesn't solve it, then it's not what I think it is. Please try clearing the app's cache and let me know how it goes.

**Comment by mariobrostech** [comment] 2024-01-31 20:28
Thanks for your quick reply! Clearing the cache has indeed solved the issue. Is this something that has already been patched, or will the problem be fixed in a future update to Obtainium?

**Comment by ImranR98** [comment] 2024-01-31 20:30
Still needs to be patched - that's why the issue was reopened.

**Comment by mariobrostech** [comment] 2024-01-31 20:33
Alright, sounds good. I'll leave this issue open, in that case 🙂

**Comment by ImranR98** [comment] 2024-02-03 09:43
https://github.com/ImranR98/Obtainium/releases/tag/v1.0.2

**Closed by ImranR98** 2024-02-03 09:43 UTC
Labels: bug, TODO
