### ISSUE TITLE
Issues with some sources

### ISSUE THREAD

**Issue by E0697** [ImranR98/Obtainium#356] opened 2023-03-14 08:36 UTC
If I try to add this app https://f-droid.org/packages/com.github.muellerma.coffee , it says "Not found".

And this one https://gitlab.com/cosmosapps/stealth , it says "No APK found"

**Comment by ImranR98** [comment] 2023-03-14 14:23
Looks like this is not an Obtainium issue. For some reason, the API request for this app fails: https://f-droid.org/api/v1/packages/com.github.muellerma.coffee

That exact request ([as documented on their website](https://f-droid.org/docs/All_our_APIs/)) works for any other F-Droid app (for example https://f-droid.org/api/v1/packages/net.sourceforge.opencamera) so this is an F-Droid API issue.

**Comment by E0697** [comment] 2023-03-14 16:18
I see. Thanks for clarifying!

**Comment by ImranR98** [comment] 2023-03-15 18:07
Okay, looks like the second repo is due to a known limitation with GitLab. Duplicate of #3 (and #282).

Nothing Obtainium can do unless there is a way to get APKs from these kinds of repos.

**Closed by ImranR98** 2023-03-15 18:07 UTC

**Comment by E0697** [comment] 2023-03-16 08:06
Got it. Sorry about the duplicate!

**Comment by ImranR98** [comment] 2023-07-15 04:02
Users with GitLab API keys should now be able to add the Stealth app: https://github.com/ImranR98/Obtainium/releases/tag/v0.13.16-beta
