### ISSUE TITLE
support for liteapks.com

### ISSUE THREAD

**Issue by Janekknaf** [ImranR98/Obtainium#1656] opened 2024-06-04 18:21 UTC
Hi 
I would like to request the addition of support for liteapks.com. Liteapks is a platform with a group of experienced modders who provide modded APKs for free. They have a large community with almost 800k members in their TIelegram group. They have their own app, but it doesn't have notifications about updates.

**Comment by ImranR98** [comment] 2024-06-04 18:26
Duplicate of #1239

**Closed by ImranR98** 2024-06-04 18:26 UTC
Labels: enhancement, to check
