### ISSUE TITLE
Endless updating

### ISSUE THREAD

**Issue by LSD4K** [ImranR98/Obtainium#310] opened 2023-02-20 12:02 UTC
This is the second time. I can immediately say that the problem solves the suspension of the application. But I don't want to do this every time.
1.The application constantly requires updating and the update icon does not disappear.![Screenshot_20230220-144923.png](https://user-images.githubusercontent.com/125026611/220099669-6cc43e24-047d-4c4a-b28d-5ef55295ddbe.png)

2.Trying to understand what the problem is I noticed that the version of the application is higher than the version it offers to install![Screenshot_20230220-144911.png](https://user-images.githubusercontent.com/125026611/220100006-2580c2d6-902f-4ac5-ac6f-57f3959bd851.png)

3.Going to the github, I found that version 3.3.1 is not in the releases. This version does not exist at all![Screenshot_20230220-144836.png](https://user-images.githubusercontent.com/125026611/220100292-0849719f-74e7-46b4-b6c5-0b551ce3454b.png)

Most likely, the application downloads version 3.3.2 every time, but the Obtainium assigns version 3.3.1, which does not exist.

**Comment by bluefly000** [comment] 2023-02-20 13:39
Duplicate of #308 .

> The Paisa app's latest release has the `v3.3.1` tag even though the App's actual version is `3.3.2`. Note that the tag is important, not the release title.
> 
> Not an Obtainium issue; needs to be fixed by the dev.

Or how about using the "No version detection" option? At least you can avoid the constant display of updates (although the correct version installed on the device will not be displayed).

**Closed** 2023-02-20 13:53 UTC
