### ISSUE TITLE
v0.5.8.b - Getting error notification for background updates when in flight mode

### ISSUE THREAD

**Issue by rak-rak** [ImranR98/Obtainium#55] opened 2022-10-10 06:50 UTC
Backup update checking interval is set. When at night the flight mode of the device is enabled, I will get a error notification.

I would expect that Obtainium waits until there is a data connection (WiFi or mobile).
(Tested on Android 12)

**Comment by ImranR98** [comment] 2022-10-10 17:13
It's supposed to. I left a phone on airplane mode for about 7 hours (interval 1 hour) and did not see any errors (checking logs confirmed that update checking did not run). Once I disabled airplane mode, it ran the task, so I haven't been able to reproduce the error.
What exact error message do you get? How many Apps do you have?

**Comment by S7venLights** [comment] 2022-10-10 17:46
It may be a notification for when obtainium finds no updates

**Comment by rak-rak** [comment] 2022-10-11 06:55
I have 12 apps in Obtainium. 11 from github.com, 1 from f-droid.

This is the error message in the morning when in flight mode during night:

"Error checking for updates
Failed host lookup" api.github.com'  "

**Comment by S7venLights** [comment] 2022-10-11 07:40
Oh i've seen that error too when disconnected, but thought nothing of it because I knew why it was happening.

**Comment by S7venLights** [comment] 2022-10-12 06:14
By the way I left my phone on last night but with no data connection in airplane mode. Got this error over night: Error checking for updates, Failed host lookup:  'api.github.com'

**Comment by rak-rak** [comment] 2022-10-12 06:37
Tested now. v0.5.9-beta:
The error message itself was improved, see screenshot: https://bilderupload.org/image/d34a56323-screenshot-20221012-07504.png

But it still shows up, the issue persists. Usually an app should not show error messages, when there is no data connection. Imagine every app would show such error messages in flight mode. ;)

Didn't test v0.5.8.10-beta. But this issue seems to be still open.

**Comment by ImranR98** [comment] 2022-10-12 13:48
What version of Android is it? I can't replicate the issue on Android 13, will try with older versions.

**Comment by rak-rak** [comment] 2022-10-12 16:47
As mentioned in first post: I'm using Android 12 (Samsung Tab S6).

**Comment by S7venLights** [comment] 2022-10-12 18:07
I'm on 12 pixel graphene OS but I'm not getting the errors he's getting.

**Comment by ImranR98** [comment] 2022-10-12 20:58
I was not able to replicate this either, on a stock Android 10 emulator this time. It should respect the [work constraints](https://developer.android.com/topic/libraries/architecture/workmanager/how-to/define-work#work-constraints) which are set for the update task, but that's not happening in your case @rak-rak. I think this may be a device-specific bug, let's see if anyone else reports it.

**Comment by S7venLights** [comment] 2022-10-12 22:07
Well I did get the error once or twice but I think now it only happens, when wifi turns on but the VPN is still getting connection. Will see tomorrow morning

**Comment by rak-rak** [comment] 2022-10-13 07:09
Tested on another device: Samsung S22 (Android 12). Same configuration.

And didn't get an error notification.

**Comment by ImranR98** [comment] 2022-10-14 14:19
Between my Android 10 and 13 emulators, S7Lights' Pixel 3, and rak-rak's S22 and Tab, this error only seems to consistently show up on the tablet. So I'll close this in a few days as a device bug that the Obtainium can't do much to fix, unless it shows up on other devices.
You could maybe see if this bug shows up on your tablet with other Apps that use Android's WorkManager for periodic tasks (maybe Tasker or something like it, not sure).

**Comment by S7venLights** [comment] 2022-10-14 19:21
Һаѕո't happened for me lately

**Comment by rak-rak** [comment] 2022-10-15 06:58
Got the same error notification now on phone Samsung S22: https://bilderupload.org/image/764716928-screenshot-20221015-08470.jpg

Maybe important: Battery optimzation for Obtainium is disabled.

**Comment by ImranR98** [comment] 2022-10-29 17:27
This is likely fixed in the latest version: https://github.com/ImranR98/Obtainium/releases/tag/v0.6.0-beta

I'm not 100% sure since you had this issue before the changes in 0.6.0, but please give it a try. Will re-open this issue if needed.

**Closed by ImranR98** 2022-10-29 17:27 UTC
Labels: bug, needs follow up

**Comment by rak-rak** [comment] 2022-10-31 04:34
No more error notifications forum 2 nights now. Thx.
