### ISSUE TITLE
Background Task is Unreliable

### ISSUE THREAD

**Issue by BabyOilJohnson** [ImranR98/Obtainium#608] opened 2023-06-04 17:24 UTC
The update notification is not clearing after the app is updated. In early versions, it worked fine but now it's not.

**Comment by ImranR98** [comment] 2023-06-04 18:26
Could you be more specific or post a screen rec.

**Comment by BabyOilJohnson** [comment] 2023-06-05 10:48
Sorry, it's working now.

**Comment by Armaldio** [comment] 2023-07-06 09:54
Can you re-open
It seems I'm facing a similar issue
The notification persist after checking is done

![Screenshot_20230706-113821](https://github.com/ImranR98/Obtainium/assets/3089715/8be86877-d2bd-4729-a215-f0db937a9dc8)

**Comment by ImranR98** [comment] 2023-07-15 11:51
How many github apps do you have, and have you added a hithub access token? I'm guessing your github update checks are being rate limited so obtainium has to wait a while before continuing. This would probably result in the notification sticking around during the wait, but I need to double check that.

**Comment by Armaldio** [comment] 2023-07-16 07:57
You're right, I haven't a token (didn't knew I could)
I've added one, I'll see how it goes

**Comment by Armaldio** [comment] 2023-07-17 08:41
Added a token, same behavior
Is the token validated in some way ? I may not have added it correctly ?!

**Comment by ImranR98** [comment] 2023-08-05 18:27
If the token was not valid, you'd get an "unauthorized" error.

**Comment by ImranR98** [comment] 2023-08-05 18:27
Could you post app logs for when this happens

**Comment by BabyOilJohnson** [comment] 2023-08-29 10:56
> The update notification is not clearing after the app is updated. In early versions, it worked fine but now it's not.

The issue is back again. @ImranR98 can u check it.

**Comment by bbrockie** [comment] 2023-10-18 23:43
I can also confirm this issue. This notification does not clear again. Running latest version. Current time as of posting this is 00:43 just for clarification 
![Screenshot_20231019-003920_Kiwi Browser_edited](https://github.com/ImranR98/Obtainium/assets/148401570/1bc4c201-fd5f-4977-b7c7-d32dc614f613)

**Comment by ImranR98** [comment] 2023-10-18 23:45
Yeah, seems to have gotten a lot worse for me on Android 14. Is this the case for you?

**Comment by bbrockie** [comment] 2023-10-18 23:52
> Yeah, seems to have gotten a lot worse for me on Android 14. Is this the case for you?

I'm stuck on Android 12, UI 4.1. Samsung Galaxy Note10

**Comment by ImranR98** [comment] 2023-10-18 23:53
> I'm stuck on Android 12, UI 4.1. Samsung Galaxy Note10

How frequent is it for you?

**Comment by bbrockie** [comment] 2023-10-18 23:57
Maybe once or twice a day. I usually kill the app to clear it. I can be more aware of how often for the future. Thank you for such a amazing app.

**Comment by ImranR98** [comment] 2023-10-18 23:59
Could you also try opening the app (without killing it first) to see if that does anything. I've been seeing weird behaviour where the background task "pauses" for hours but resumes once I open the app. New to Android 14 so it may be a different issue to this one.

**Comment by bbrockie** [comment] 2023-10-19 00:08
Done. It still shows same notification. I have not cleared it manually nor killed the app.
But I did a applist pulldown, refreshing the update list. It shows the same beta version, but with todays release date.
Do you want me to install it or stay with my current version and test some more?

**Comment by ImranR98** [comment] 2023-10-19 00:11
You can update. Today's changes shouldn't have any effect on this.

**Comment by bbrockie** [comment] 2023-10-19 00:15
Thank you for your time and help. I had to ask, as updating would of course restart the app and remove the "stuck notification".
I will keep an eye on this issue thread and update as soon as possible if it happens again.
Wish you all a beautiful day.

**Comment by bbrockie** [comment] 2023-10-19 17:38
I updated to 0.14.31 and it seemed to work, but I have again gotten the "Checking for Updates" notification, like the one I posted a screenshot of earlier, which has now been stuck since 18:16.
Local time is now 18:38.

**Comment by ImranR98** [comment] 2023-10-28 04:21
Been banging my head on this for hours. Most other plugins seem out of date, poorly supported, or are missing features (like being able to pass data into the background task). Someone suggested using a foreground task - that's an option but seems unnecessarily complicated for something so simple. Really wish I hadn't used Flutter (not like native Android was an option). I've opened this issue for the plugin currently being used, hopefully it turns out to be a small bug: https://github.com/fluttercommunity/plus_plugins/issues/2314

**Comment by mercertom** [comment] 2023-11-01 18:37
+1 checking for updates notifications and also "attempted to update" notifications, but those are rarer and so far only for telegram and signal, which pull from their own websites instead of repositories like github or fdroid.

**Comment by bluefly000** [comment] 2023-11-15 19:56
[SCHEDULE_EXACT_ALARM permission seems to be disabled by default in Android 14](https://developer.android.com/about/versions/14/changes/schedule-exact-alarms), does this have anything to do with background tasks? I reinstalled Obtainium on Android 14 and confirmed that the "Alarm & reminder" setting has disappeared from the Settings app.

**Comment by ImranR98** [comment] 2023-12-28 08:42
I've switched to a different background task implementation which doesn't seem to have the same issues on Android 14. Works fine in my basic testing but I'd like to be more thorough before release. APKs attached below, please help test if you can (even testing on older versions of Android would be helpful):

[app-arm64-v8a-release.zip](https://github.com/ImranR98/Obtainium/files/13784751/app-arm64-v8a-release.zip)
[app-armeabi-v7a-release.zip](https://github.com/ImranR98/Obtainium/files/13784752/app-armeabi-v7a-release.zip)

**Comment by mercertom** [comment] 2023-12-28 14:29
So far working. I set to update every hour.

-------- Original Message --------

**Comment by ImranR98** [comment] 2024-01-01 02:32
Closing - seems fixed.

**Closed by ImranR98** 2024-01-01 02:32 UTC
Labels: bug, high priority

**Comment by ImranR98** [comment] 2024-01-01 02:34
> I once tried to create PAT & ended up getting shadow banned by GitHub declaring my GitHub account as "spam user". All of my comments, created issues/discussions were shadow banned completely. Llike this one: [TeamNewPipe/NewPipe#10462](https://github.com/TeamNewPipe/NewPipe/issues/10462)
> 
> I ended up creating another account & started everything from scratch. I never recommend use GitHub PATs for obtainium. Better track F-Droid repos if those app provides updates.

Just saw this comment. Obtainium just makes authenticated HTTP requests to GitHub's public API - which is the exact use case PATs were meant for, so I doubt it is responsible. Either way, not related to this issue.
