### ISSUE TITLE
garmin connect iq from apkpure can't find suitable release

### ISSUE THREAD

**Issue by jm355** [ImranR98/Obtainium#1912] opened 2024-10-17 20:59 UTC
**Prerequisites**

**Describe the bug**
When I try to add connect iq https://apkpure.net/connect-iq%E2%84%A2-store/com.garmin.connectiq it says "could not find a suitable release"

**To Reproduce**
1. open obtainium
2. tap "add app"
3. paste https://apkpure.net/connect-iq%E2%84%A2-store/com.garmin.connectiq into app source url 
4. Tap "add"
5. get error

**Screenshots and Logs**

**Please complete the following information:**
 - Device: pixel 8
 - OS: GrapheneOS
 - Obtainium Version: 1.1.27

**Additional context**

**Comment by DwainZwerg** [comment] 2024-10-18 10:28
Can you try if you can install Garmin Connect iq manually?

**Comment by jm355** [comment] 2024-10-18 13:13
hmm, looks like with connect iq, it either downloads a .xapk file if I choose the latest version, or downloads an apkpure store .apk

**Comment by jm355** [comment] 2024-10-18 13:16
It's a similar thing with aptoide for garmin express. It downloads an apk for the aptoide store app

**Comment by ImranR98** [comment] 2024-10-20 15:56
In the APKPure case, it looks like the ™ in the app title is causing problems. Will be fixed in the next release.
For Aptoide, they're providing an APK that isn't compatible - not much we can do about that.
And yeah, in both cases the website UI really wants you to download the app store instead of the APK you want directly.

**Comment by ImranR98** [comment] 2024-10-20 20:46
Should work now: https://github.com/ImranR98/Obtainium/releases/tag/v1.1.28

Note you still probably won't be able to install the app because it is incompatible. I've seen this happen with other APKPure/Aptoide apps, not clear what the issue is but it isn't an Obtainium bug. It's inconsistent - for TikTok, for example, only some versions are incompatible.

**Closed by ImranR98** 2024-10-20 20:46 UTC
Labels: bug, TODO, source-specific
