### ISSUE TITLE
可以添加https://liteapks.com/吗

### ISSUE THREAD

**Issue by Tree-New-Beee** [ImranR98/Obtainium#1428] opened 2024-02-27 00:47 UTC
**Prerequisites**

**Describe the feature**

**Describe alternatives you've considered (if applicable)**

**Additional context**

**Comment by DwainZwerg** [comment] 2024-02-27 12:12
Could you answer the following questions: Use the site HTML instead of JavaScript, or has the site an API? Where can I find the API?

**Comment by ImranR98** [comment] 2024-02-28 04:48
Also a duplicate of #1239 (guess they've changed the design since then which is good).

**Closed by ImranR98** 2024-02-28 04:48 UTC
Labels: enhancement, to check

**Comment by DwainZwerg** [comment] 2024-04-01 20:51
In the meantime, the version extraction is working again or is still not working (see https://github.com/ImranR98/Obtainium/issues/1510#issuecomment-2030531069).
