### ISSUE TITLE
[Feature request] update apps as soon as they come out

### ISSUE THREAD

**Issue by Sukii23** [ImranR98/Obtainium#573] opened 2023-05-17 13:28 UTC
An option in settings to update apps as soon as they have updates. as an example, Obtainium could download the app when it has an update and notify the user that there is an update to be done through the notification (with the file ready to be installed).

And so download all apps that have updates automatically, informing the user if there is one or more apps ready to be updated.

And if the user prefers, he doesn't need all Obtainium apps to be updated, but only those he selects in the automatic updates settings.

I hope my idea is useful!
I really like the idea and development of this app, I hope I can contribute in some way.

**Comment by ImranR98** [comment] 2023-05-18 01:35
Mostly a duplicate of #344 will track the app-specific toggle as part of that issue.

**Closed by ImranR98** 2023-05-18 01:35 UTC
