### ISSUE TITLE
have a recommended app index

### ISSUE THREAD

**Issue by RustoMCSpit** [ImranR98/Obtainium#689] opened 2023-07-16 16:42 UTC
in the add app section, there should be a scrollable popular recommendation list for apps under different headers 'e.g. music player, file manager, text editor, etc.'. it should display the author, license, most recent update, and when yiu download it you should be askef from whag source

**Comment by RustoMCSpit** [comment] 2023-07-16 16:43
heres a random list i found online: https://github.com/offa/android-foss

**Comment by ImranR98** [comment] 2023-07-16 17:06
Duplicate of part of #68, which has been re-opened

**Closed by ImranR98** 2023-07-16 17:06 UTC
