### ISSUE TITLE
Login OTPs being received from unknown sources for signal/molly downloaded from obtainium. 

### ISSUE THREAD

**Issue by kergitthecoder** [ImranR98/Obtainium#1225] opened 2023-12-31 17:09 UTC
**Prerequisites**

**Describe the bug**
<!— When logging into signal/molly, OTP from random sites are received but nothing form signal (happens only with obtainium downloads)-->

**To Reproduce**
1. Download signal/ molly from obtainium, using official sources (signal.org and molly foss github respectively) and install.
2. open signal/molly, enter your phone number and request OTP
3. Wait. 
4. You should receive random otps from random sites you have never heard of, but nothing from signal.

**Please complete the following information:**
 - Device: <!— [Redmi note 8] -->
 - OS: <!— [CrDroid (A14 vanilla)] -->
 - Obtainium Version: <!— [0.15.1] -->

**Additional context**
<!— I was able to reproduce this issue every time I tried it. 3 times with signal, twice with molly. I can confirm this is not a signal side issue, because signal from google play/ molly foss from f droid repo work fine. -->

**Comment by ImranR98** [comment] 2023-12-31 20:33
That is very weird. Can you try downloading the Signal APK manually from their website: https://signal.org/android/apk/

**Comment by kergitthecoder** [comment] 2024-01-01 12:50
It works, official apk and play store both work fine. I was confused because obtainium and official apk both had the same sha256sums. Idk what went wrong here. not sure if this is helpful, but
![Screenshot_20231231-190227_QKSMS](https://github.com/ImranR98/Obtainium/assets/113348861/186393bd-6f0e-4bbf-9033-f0a7d9baf9b4)
![Screenshot_20240101-045224_QKSMS](https://github.com/ImranR98/Obtainium/assets/113348861/d024716a-63ea-486d-93b2-2790f9aa345f)
![Screenshot_20240101-045230_QKSMS](https://github.com/ImranR98/Obtainium/assets/113348861/83402f33-1b1b-44f5-86d3-31d87f49cb6a)
 here are some of the otps i received.

**Comment by ImranR98** [comment] 2024-01-01 12:58
Definitely very strange - there's nothing in Obtainium that should have any effect on this (especially if it's the exact APK as shown by the hash). Do you have another device to test with? Wondering if the same thing happens.

**Comment by kergitthecoder** [comment] 2024-01-01 17:33
unfortunately rn I have only one android device, but I’ll see what i can do. For now, since nobody else has commented I guess I am the only one facing this. So I think this should be closed. Because the more i dig into this, more confusing it gets. There were 2 possibilities -  1. bad apk;hash match means the apk is fine.
2. Received random otp coincidently ;should’ve received signal otp soon or later but didn’t. 
Without testing on more devices, we can’t know fs. If I manage to get more tests done, I’ll get screen recordings, logs etc.

**Comment by ImranR98** [comment] 2024-01-01 17:38
Yeah, I find it very unlikely to be caused by Obtainium - hopefully you can narrow down the cause (maybe it's specific to your device or even phone number). Closing for now.

**Closed by ImranR98** 2024-01-01 17:38 UTC
Labels: bug, needs follow up
