### ISSUE TITLE
Consistently leaves notifications when checking for updates and attempting updates

### ISSUE THREAD

**Issue by mercertom** [ImranR98/Obtainium#1059] opened 2023-11-01 18:25 UTC
**Describe the bug**
I'll often find an "orphan" notification that it's "checking for updates" that is several minutes to several hours old. This is in contrast to the "desired" or "healthy" behavior where it checks for updates and destroys the notification when it finishes checking for updates.

**To Reproduce**
Set it to auto-check for updates at any interval
Don't check your phone for at least a few minutes during the time it'd check for updates
See if you can get "orphan" notifications that it's "checking for updates" that hang around hours after the check is definitely over (or maybe that's the bug, that the process isn't finishing so it never cleans up the notifications after itself?)

**Screenshots and Logs**

**Please complete the following information:**
Pixel 4a 5g GrapheneOS latest Obtanium, updated several times a day

**Comment by ImranR98** [comment] 2023-11-01 18:28
Duplicate of #608

**Closed** 2023-11-01 18:28 UTC
Labels: bug, to check
