### ISSUE TITLE
apkpure: cannot install FGO English using xapk

### ISSUE THREAD

**Issue by soredake** [ImranR98/Obtainium#1794] opened 2024-08-17 04:20 UTC
**Prerequisites**

**Describe the bug**
The APK could not be parsed (incompatible or partial download) [Fate/GO]

**To Reproduce**
1. Add https://apkpure.net/fate-grand-order-english/com.aniplex.fategrandorder.en to applications list
2. Try to install it
3. The APK could not be parsed (incompatible or partial download) [Fate/GO]

**Screenshots and Logs**
![изображение](https://github.com/user-attachments/assets/500cdcb2-8f0b-4c8c-a7e6-1d73bfda0e52)

<details>
<summary>Logs</summary>
2024-08-17 07:10:30.360: info: Could not install APK from XAPK '/storage/emulated/0/Android/data/dev.imranr.obtainium/cache/com.aniplex.fategrandorder.en-830187219.xapk-dir/com.aniplex.fategrandorder.en.apk': Incompatible

2024-08-17 07:10:30.369: info: Could not install APK from XAPK '/storage/emulated/0/Android/data/dev.imranr.obtainium/cache/com.aniplex.fategrandorder.en-830187219.xapk-dir/config.arm64_v8a.apk': The APK could not be parsed (incompatible or partial download)

2024-08-17 07:10:30.370: error: Incompatible [Fate/GO]

The APK could not be parsed (incompatible or partial download) [Fate/GO]

2024-08-17 07:11:54.468: info: Could not install APK from XAPK '/storage/emulated/0/Android/data/dev.imranr.obtainium/cache/com.aniplex.fategrandorder.en-830187219.xapk-dir/com.aniplex.fategrandorder.en.apk': Incompatible

2024-08-17 07:11:54.476: info: Could not install APK from XAPK '/storage/emulated/0/Android/data/dev.imranr.obtainium/cache/com.aniplex.fategrandorder.en-830187219.xapk-dir/config.arm64_v8a.apk': The APK could not be parsed (incompatible or partial download)

2024-08-17 07:11:54.477: error: Incompatible [Fate/GO]

The APK could not be parsed (incompatible or partial download) [Fate/GO]

2024-08-17 07:17:22.300: info: Could not install APK from XAPK '/storage/emulated/0/Android/data/dev.imranr.obtainium/cache/com.aniplex.fategrandorder.en-830187219.xapk-dir/com.aniplex.fategrandorder.en.apk': Incompatible

2024-08-17 07:17:22.314: info: Could not install APK from XAPK '/storage/emulated/0/Android/data/dev.imranr.obtainium/cache/com.aniplex.fategrandorder.en-830187219.xapk-dir/config.arm64_v8a.apk': The APK could not be parsed (incompatible or partial download)

2024-08-17 07:17:22.314: error: Incompatible [Fate/GO]

The APK could not be parsed (incompatible or partial download) [Fate/GO]

2024-08-17 07:17:31.185: info: Could not install APK from XAPK '/storage/emulated/0/Android/data/dev.imranr.obtainium/cache/com.aniplex.fategrandorder.en-830187219.xapk-dir/com.aniplex.fategrandorder.en.apk': Incompatible

2024-08-17 07:17:31.193: info: Could not install APK from XAPK '/storage/emulated/0/Android/data/dev.imranr.obtainium/cache/com.aniplex.fategrandorder.en-830187219.xapk-dir/config.arm64_v8a.apk': The APK could not be parsed (incompatible or partial download)

2024-08-17 07:17:31.193: error: Incompatible [Fate/GO]

The APK could not be parsed (incompatible or partial download) [Fate/GO]

2024-08-17 07:19:33.902: info: Could not install APK from XAPK '/storage/emulated/0/Android/data/dev.imranr.obtainium/cache/com.aniplex.fategrandorder.en-830187219.xapk-dir/com.aniplex.fategrandorder.en.apk': Incompatible

2024-08-17 07:19:33.921: info: Could not install APK from XAPK '/storage/emulated/0/Android/data/dev.imranr.obtainium/cache/com.aniplex.fategrandorder.en-830187219.xapk-dir/config.arm64_v8a.apk': The APK could not be parsed (incompatible or partial download)

2024-08-17 07:19:33.922: error: Incompatible [Fate/GO]

The APK could not be parsed (incompatible or partial download) [Fate/GO]
</details>

**Please complete the following information:**
 - Device: Motorola Edge 40
 - OS: Android 14
 - Obtainium Version: [1.1.19](https://github.com/ImranR98/Obtainium/releases/tag/v1.1.19)

**Additional context**

**Comment by ImranR98** [comment] 2024-08-20 01:05
Likely a duplicate of #682 (incomplete XAPK support).

**Closed by ImranR98** 2024-08-20 01:05 UTC
Labels: bug, to check

**Comment by ImranR98** [comment] 2024-08-20 01:31
On closer inspection though, it seems like this in case, there might be a problem with the app itself? I just tried manually extracting the XAPK on my phone and installing the contents. Got an "incompatible" error even though the file is supposed to be arm64-v8a. Or maybe I'm missing something - still not sure how XAPKs work exactly.

Could you try installing through a method you've used successfully before with other XAPKs (if you have one)?

**Comment by soredake** [comment] 2024-08-20 03:59
> On closer inspection though, it seems like this in case, there might be a problem with the app itself? I just tried manually extracting the XAPK on my phone and installing the contents. Got an "incompatible" error even though the file is supposed to be arm64-v8a. Or maybe I'm missing something - still not sure how XAPKs work exactly.
> 
> Could you try installing through a method you've used successfully before with other XAPKs (if you have one)?

I can successfully update fgo to 2.67.0 using APKPure installer and their xapk.
