### ISSUE TITLE
Better version detection

### ISSUE THREAD

**Issue by ghost** [ImranR98/Obtainium#946] opened 2023-09-30 07:21 UTC
Hi, can I ask why Obtainium does not detect the version very well for apps that do not have a standard format? 

This will cause some issues especially when it thinks that the app is updated but the same version was installed as mentioned in #941, can't it just extract the string from the system and compare it to the one indicated on the site? 

I know I'm missing something so a brief explanation would be very helpful so I can understand the mechanism.

Thank you.

**Comment by ImranR98** [comment] 2023-09-30 11:31
> can't it just extract the string from the system and compare it to the one indicated on the site?

That's where the problem is - the string that comes from the system is the real version string, while the string that comes from GitHub is just the Git tag for that release (for other sources it is similar - a string extracted from somewhere that uniquely identifies a release but isn't necessarily the exact version string for that release). Most developers use version strings as Git tags which is great, but some don't. Some do, but add extra info to the Git tag.

For example, you could have an any of these cases:
1. App version `0.14.21` but source says `v0.14.21-beta`: https://github.com/ImranR98/Obtainium/releases/tag/v0.14.21-beta
2. App version `2.12.8-2+free` but source says `2.12.8-2`: https://git.singpolyma.net/cheogram-android/refs/2.12.8-2
3. App version `102.2.1-Release (12.5.6)` (really, that whole thing is the OS-reported "version") but source says nothing - no version string is provided by this HTML source so a URL hash is used instead as the release identifier: https://www.torproject.org/download/
4. App version `1` but source says `v10`: https://github.com/ImranR98/Obtainium/issues/404#issuecomment-1492007484

So there is no guarantee that the OS-provided "real" version will be in any way comparable to the source-provided "version" which is really just needs to uniquely ID a release to enable update notifications - it doesn't need to be a real version string.

In some cases, where the strings seem to both conform to some standard format, like `x.y.z` or `x.y`, we can make the comparison. In some cases Obtainium can strip off extra parts from the source string if it would result in a standard version (like how `v` and `-beta` are removed from Obtainium's `v0.14.21-beta`), then it can make the comparison.

This is how the various "standard" versions are generated: https://github.com/ImranR98/Obtainium/blob/main/lib/providers/apps_provider.dart#L64
It's always possible to expand this to add more support but we'd need to be careful (see #136 where there was a lot of trial and error figuring this out). For example if an app reports `1.2` but the source says `1.2-4`, should we strip off the number `4` and say the two are the same so no update? Right now, that wouldn't happen since we are only allowed to remove specific words and prefixes.

So in general if Obtainium can't resolve the differences between the two strings to a standard format, it disables version detection and hopes the user never has to update the app externally (in which case they would probably never notice the difference).

I'm not sure why you mentioned #941 though, I don't think version detection makes any difference there.

**Comment by ImranR98** [comment] 2023-09-30 11:40
Feel free to re-open if needed.

**Comment by ImranR98** [comment] 2023-09-30 13:47
Are you confident this is true for all APKPure, Aptoide, and Uptodown apps? It is for the ones I checked, just making sure.

**Comment by ImranR98** [comment] 2023-09-30 13:49
Also I think I get how this relates to #941 now. Wouldn't fix the issue but would make sure the update would be retried later.

**Comment by ImranR98** [comment] 2023-09-30 14:21
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.22-beta

I'll update the comment above with this info so I can link to to explain version detection it in the future.

**Comment by silverwings15** [comment] 2023-10-09 04:03
having trouble with this one myself

![image](https://github.com/ImranR98/Obtainium/assets/10742312/366a0aef-53d6-4769-a6fa-5608d4522fd1)

**Comment by silverwings15** [comment] 2023-10-09 04:20
oh i see. in that case i'll do so right away

**Comment by silverwings15** [comment] 2023-10-09 04:35
whoops, saw this a little too late. let me go ahead and close it

**Comment by M00NJ** [comment] 2023-10-09 12:20
I'm also experiencing issues with obtainium not being able to detect the latest version of apps from GitHub and IzzyOnDroid (See screenshots, I manually installed the actual latest versions). In the case of ConnectYou I checked if the version string is the same as the tag on GitHub and it is, so I don't know where this issue is comming from... :/
![Screenshot_20231009-135936](https://github.com/ImranR98/Obtainium/assets/82398591/6e6f0a03-1aec-4ed5-9f73-b844675ee27a)
![Screenshot_20231009-135947](https://github.com/ImranR98/Obtainium/assets/82398591/34222907-8d02-4c50-b648-edb77f60e1db)

**Comment by M00NJ** [comment] 2023-10-10 08:15
Thanks for the InnerTune link. I missed that the FOSS flavor is available on github as well now. I'll switch to that in Obtainium. As for ConnectYou, I'm one of the devs that works on it. I didn't create this release, but checked and everything looks right. I will ask to handle the next release. Let's see if Obtainium detects it when it's out. If not we'll have to take a closer look at this.

**Comment by ImranR98** [comment] 2023-10-17 15:57
@unbranched could you also see if the package ID of your existing install matches the one found by Obtainium? You might be able to see it in your OS settings under Apps (depends on the OS)?

**Comment by ImranR98** [comment] 2023-10-17 15:59
Just saw your earlier comment. If your F-Droid version of the app has the `.free` suffix in the package ID, then it is a totally separate app as far as the OS is concerned. You could even install both side by side. So Obtainium not detecting it is totally expected.

**Comment by henosch** [comment] 2024-01-10 14:13
![Screenshot_20240110-151225.png](https://github.com/ImranR98/Obtainium/assets/59366586/eced4d0d-ed44-4634-b0b4-293c8e3d9ee1)

**Comment by ImranR98** [comment] 2024-01-10 14:19
@henosch https://github.com/ImranR98/Obtainium/wiki#version-detection

**Comment by The-Kyber** [comment] 2024-04-09 18:06
I am thinking about a solution to all these problems at once, correct me if I am wrong in something.

Let's call the verison we get from the website `Web Version` and the one we get from the OS `OS Version`.

Instead of comparing them directly we will combign them in a single string `Web Version` `-` `OS Version` and storing them for each app, everytime it checks it will compare the string it stored with the one it will generate at that moment of checking.

Let's say a new version was released `New Web Version`, it will be like this: `Web Version` `-` `OS Version` (which is stored) != `New Web Version` `-` `OS Version` (which is newly generated), and after istallation it will be replaced.

I hope I made clear.

**Comment by ImranR98** [comment] 2024-04-09 18:23
@The-Kyber not sure I understand, could you walk through an example?

Remember the goal is to reliably detect changes made to an app outside of Obtainium. Let's say Obtainium thinks version 0.1 of an app is installed. If you install version 0.2 using the Play Store, Obtainium should detect that and switch it's own internal record to 0.2 as well.

**Comment by The-Kyber** [comment] 2024-04-09 19:11
Well, I never thought about detecting the version if anything happened outside of Obtainium, and the method I talked about will not work.

But when using only Obtainium to handle the installation it is gonne be like (just so you can understand me maybe you will have an idea on how to improve it to make it detect changes from outside)

You have the verison 0.1 the first time from APKPure and when it is installed Obtainium is going to create the variable we talked about and it is going to be `0.1-0.1`, half from the OS and half from the site.

When checking for an update and let's say version 0.2 has been released, Obtainium is going to create a new string (just for comparison, it will not be stored), it will get `0.2-0.1`, when compared to `0.1-0.1` it will obviously find a difference that will make it know there is an update, after intsalling the update it will store a new variable that has the value `0.2-0.2`, and if there is no update it will generate the disposable one and get `0.2-0.2` and compare it to the one is has already stored from the previous update which is `0.2-0.2` and they are the same as you see so no updates are available.

Note that this process should be hidden from the user and the version should be displayed as Obtainium does it now, this method is only for checking.

I will tell you if I think about anything that will solve the problem of updating the app outside of Obtainium.

I know some sources are working very good but I am looking for something to solve everything at once, especially for apps from GitHub and GitLab.

**Comment by ImranR98** [comment] 2024-04-09 19:16
I don't see the problem you're trying to solve. If we're only concerned about update tracking within Obtainium, we don't need to deal with the OS version at all. We don't even need a version string of any kind - any release-specific ID will do, like timestamps, url hashes, etc. (we already use those kinds of identifiers in some cases).

**Comment by The-Kyber** [comment] 2024-04-09 19:26
I am trying to make it sure about the version, so the user will not bother thinking about the apps that do not have good detection.

Anyways, thank you

**Closed** 2024-04-09 19:30 UTC
Labels: enhancement
