### ISSUE TITLE
Issues adding PIA github

### ISSUE THREAD

**Issue by Nemes15** [ImranR98/Obtainium#1238] opened 2024-01-03 01:01 UTC
**Prerequisites**
Done and added a link to something related
done

**Describe the bug**
I am on no way able to add the PIA github

**To Reproduce**
1. Go to Add App
2. Tap on Add Source URL or search (and find) https://github.com/pia-foss/mobile-android
3. Tap add
4. See error --> "Could not find a suitable release"

**Screenshots and Logs**

easy to reproduce

**Please complete the following information:**
 - Device: Samsung S20
 - OS: Default not rooted
 - Obtainium Version: 0.15.03

**Additional context**
Link to Regex issues with the releases https://github.com/pia-foss/mobile-android

I'm new to Obtainium but had no issues adding any other links. 
I left all settings to default. The Wiki did not help but I might be doing it wrong since there is a post about regex saying it works but no clarification on how they made it work.

Do note that "latest release" is not the latest on their github https://github.com/pia-foss/mobile-android/releases

The latest version is shown here https://github.com/pia-foss/mobile-android/commits/master/

And is available as source but not as APK, this is their mistake, it is shown correctly on their website with download link 
https://www.privateinternetaccess.com/installer/download_installer_android

Could you please help me (and future new obtanium users) by explaining or fixing how this process works :)

**Comment by ImranR98** [comment] 2024-01-03 01:28
The GitHub releases don't have APK files attached so it doesn't make sense to try adding the GitHub URL to Obtainium (regardless of whether it is the latest).

You can use the link on their website instead, but (as written in the Wiki) this should be the URL of the webpage which contains an APK link and not the APK link itself.

So this URL should work: https://www.privateinternetaccess.com/download/android-vpn-app

**Comment by Nemes15** [comment] 2024-01-03 01:37
This, however, only gives an "estimate" version.
I tried adding the link you mentioned and it says

Latest version 808577739
Installed version 677338840

While I have the latest version installed :(

Is there a way to work around this? Since receiving outdated updates is not much help, however, there are regular updates and are important to security software. This is not your problem of course, but help users if it is not too much work.

The direct link I provided also shows the version and sha which could be scraped

**Comment by ImranR98** [comment] 2024-01-03 02:15
Yes, you could use version detection to grab the real version from the link. Or you could mark the app as updated and continue using the pseudo-version. Please read and understand the wiki as it explains this in more detail.

**Comment by Nemes15** [comment] 2024-01-03 02:51
I had to mark it as pseudo-version (saying the app is up to date) since when I try to open the settings on the app I get a large empty box (bug?).
When checking the app it's on HTML, which is expected, but 'no version detection' is on and I am unable to change that.

I read the wiki, do I understand everything, no I do not. But most of it I do. I'm sorry.

**Comment by ImranR98** [comment] 2024-01-03 03:51
Could you create an export on the import/export page and attach it?

**Comment by Nemes15** [comment] 2024-01-03 04:12
Export did not work, or I did it incorrectly. But here are two screenshots and the installed APK is in the link. It should be easy to reproduce.
![Screenshot_2024](https://github.com/ImranR98/Obtainium/assets/77677125/045b1e00-fcdf-415a-b190-ca68a0b64a4a)
![Screenshot_202401](https://github.com/ImranR98/Obtainium/assets/77677125/86c7a49e-d3be-40fe-9f45-7e3fc5c5ad0e)

**Comment by ImranR98** [comment] 2024-01-03 04:14
The grey box is definitely a bug but I can't tell what the problem is without an export. What's happening when you try exporting?

**Comment by Nemes15** [comment] 2024-01-03 04:21
It was my fault, I tried a "security protected folder" and did not notice lol
This is the export
[obtainium-export-2024-01-03T05-17-47.031677.json](https://github.com/ImranR98/Obtainium/files/13815660/obtainium-export-2024-01-03T05-17-47.031677.json)

**Comment by ImranR98** [comment] 2024-01-03 23:24
The grey box should be gone in the next release (you will need to refresh the app list first).

Then you can enable version detection after setting "Version Extraction Regex" to `android-(.+)-` and "Match Group" to 1.

**Comment by ImranR98** [comment] 2024-01-04 01:39
Grey box should be fixed after a refresh: https://github.com/ImranR98/Obtainium/releases/tag/v0.15.4-beta

**Closed by ImranR98** 2024-01-04 01:39 UTC
Labels: bug, TODO
