### ISSUE TITLE
Forbidden when trying to add HTML source

### ISSUE THREAD

**Issue by D3SOX** [ImranR98/Obtainium#955] opened 2023-10-04 15:09 UTC
**Prerequisites**

None

**Describe the bug**

Obtainium is unable to fetch an HTML site with links to APKs

**To Reproduce**
1. Try to add `https://auroraoss.com/AuroraStore/Nightly/` as a source
2. See error

**Screenshots and Logs**

![Screenshot_20231004-170615_Obtainium.png](https://github.com/ImranR98/Obtainium/assets/24937357/fbf1e0a5-5349-49cb-b2df-3d8cf47ebaf0)

**Please complete the following information:**
 - Device: OnePlus 8T
 - OS: Lineage for microG
 - Obtainium Version: 0.14.22

**Additional context**

Maybe the web server refuses access because of the user agent or any other HTTP headers Obtainium uses to fetch it.

I also tried to play around with the additional options like setting the regex but without success

**Comment by ImranR98** [comment] 2023-10-04 23:01
Duplicate of #709

**Closed by ImranR98** 2023-10-04 23:01 UTC

**Comment by D3SOX** [comment] 2023-10-04 23:40
Oops, sorry for creating a duplicate, should've searched before, thanks for pointing me in the right direction tho
