### ISSUE TITLE
uptodown: hostname mismatch when trying to update Fate/GO English

### ISSUE THREAD

**Issue by soredake** [ImranR98/Obtainium#1819] opened 2024-09-05 06:11 UTC
**Prerequisites**

**Describe the bug**
![изображение](https://github.com/user-attachments/assets/33e2ac13-0695-4a12-8c7d-bf7658241554)
When trying to update FGO english.

**To Reproduce**
1. Add `https://fate-grand-order.en.uptodown.com/android/download` to obtainium
2. Install
3. Wait for update
4. Hostname mismatch error

**Screenshots and Logs**
![изображение](https://github.com/user-attachments/assets/7391402b-0e32-47e5-913d-ad868ea0e6fa)
```
2024-09-05 09:09:31.573: error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: Hostname mismatch(handshake.cc:393)) [Fate/GO]
```

**Please complete the following information:**
 - Device: Moto Edge 40
 - OS: Android 14
 - Obtainium Version: [v1.1.20](https://github.com/ImranR98/Obtainium/releases/tag/v1.1.20)

**Additional context**

**Comment by ImranR98** [comment] 2024-09-08 06:37
Duplicate of #1458

**Closed by ImranR98** 2024-09-08 06:37 UTC
Labels: bug, to check
