### ISSUE TITLE
"Could not find a suitable release" when attempting to add Gitlab repo

### ISSUE THREAD

**Issue by Gunther0042** [ImranR98/Obtainium#594] opened 2023-05-28 10:57 UTC
I get a "Could not find a suitable release" message when trying to add the Tiny Tiny RSS Android app repo from Gitlab (https://gitlab.tt-rss.org/tt-rss/tt-rss-android/-/releases) to Obtainium. This may be because the apk files in that repo are included as download links rather than as assets, I'm not sure.

**Comment by ImranR98** [comment] 2023-05-30 23:45
Yes, that's why. Duplicate of #3 (and others).

**Closed by ImranR98** 2023-05-30 23:45 UTC

**Comment by schklom** [comment] 2023-06-11 13:52
@Gunther0042 If it helps, I mirror that repository daily and build the apk file if it changes.
That GitHub repo works on my phone with Obtainium. Use/duplicate it if you want :)
https://github.com/schklom/tt-rss-android, with the GitHub Action at https://github.com/schklom/Mirror-workflows/blob/main/.github/workflows/Sync%2BBuild%2BRelease%20tt-rss-android.yaml

**Comment by Gunther0042** [comment] 2023-06-11 14:07
@schklom Thanks for much for this! I actually got an in-app notification from TTRSS last time there was an update available, so hopefully that will take care of things for now.

Out of curiosity, since you build it yourself, that means it's not signed with the developer's keys?

**Comment by schklom** [comment] 2023-06-11 15:39
> since you build it yourself, that means it's not signed with the developer's keys?

@Gunther0042 It's not, and I doubt the dev would give me his signing keys, but I don't really care because I own the repository.
If you don't trust me (and you shouldn't, I'm a random stranger to you), copy my repository + GitHub Action and build your own apk.
You would need to register a PAT on GitHub to let the Action update your repo, but that's about it.
