### ISSUE TITLE
Add option to share Github repo URL to Obtanium

### ISSUE THREAD

**Issue by pective** [ImranR98/Obtainium#1955] opened 2024-11-08 10:40 UTC
**Describe the feature**
When adding a new app into obtanium, I find it kind if tedious to press the share button in the github repo, copy the url, open obtanium and add the app. What if instead we could just press the share button, and from the share menu select obtanium instead of manually adding the app? I think it would make the process of adding an app easier.

**Additional context**
![Screenshot_20241108-113622-ezgif.com-censor.png](https://github.com/user-attachments/assets/0112c661-daf3-4bc9-aa31-fcee820cf6d2)

**Comment by ImranR98** [comment] 2024-11-08 18:23
This is a duplicate of an existing issue.

**Closed by ImranR98** 2024-11-08 18:23 UTC
Labels: enhancement, to check
