### ISSUE TITLE
Feature Request: track actions

### ISSUE THREAD

**Issue by RSDamasceno** [ImranR98/Obtainium#233] opened 2023-01-21 12:15 UTC
Apps like CorePatch and TwiFucker use the actions tab for some "experimental" updates. Would it be possible to keep track of these updates as well? 

For reference:
https://github.com/LSPosed/CorePatch/actions
https://github.com/Dr-TSNG/TwiFucker/actions

**Comment by ImranR98** [comment] 2023-01-22 09:42
Duplicate of #102

**Closed by ImranR98** 2023-01-22 09:42 UTC
