### ISSUE TITLE
Installing packages through a third party apk installer

### ISSUE THREAD

**Issue by serrq** [ImranR98/Obtainium#520] opened 2023-05-01 03:30 UTC
I would like to install (manually) the apk(s) downloaded from Obtainium.

I don’t want to give too much freedom to an app and in particular "installation sources" is a permission that should not be given to any app.

So I ask that the possibility be offered to use the default installer inside the operating system as an installation method (optionally). Or a third party one (Droid-ify is already a installation source).

**Comment by ImranR98** [comment] 2023-05-02 03:57
There's a few things here that conflict with your title, so I'll address them separately.

>  **Installing packages through a third party apk installer** 

Duplicate of #517.

> I would like to install (manually) the apk(s) downloaded from Obtainium.

APKs are cached in `/Android/data/dev.imranr.obtainium` so you can get them from there (if you click install, they are deleted so this only works if you cancel the install prompt).

> I don’t want to give too much freedom to an app and in particular "installation sources" is a permission that should not be given to any app.

Android won't let anything install a new App without your permission - by clicking accept on the install prompt. So granting the permission is fine as you can still cancel the popup.

> So I ask that the possibility be offered to use the default installer inside the operating system as an installation method (optionally).

The default OS API is already being used. If you mean the old installer (which is considered a "legacy" method), refer to #517.

> Or a third party one (Droid-ify is already a installation source).

Not sure what this means. Droid-ify also uses either the OS API or the old package installer (excluding root options). So you can't pass Obtainium's install requests to Droid-ify as it is not capable of installing anything on its own - it has to use the options the OS gives it.

**Closed by ImranR98** 2023-05-02 03:57 UTC
