### ISSUE TITLE
Backup downloaded apks

### ISSUE THREAD

**Issue by stdedos** [ImranR98/Obtainium#1745] opened 2024-07-23 19:22 UTC
**Prerequisites**

**Describe the feature**

"Just in case", I would like to save all downloaded/installed apks in a `Downloads/` folder.

Use it e.g. if the apk does not exist anymore, downgrade if "something happened" and have the apks there already, etc

**Describe alternatives you've considered (if applicable)**

**Additional context**

* https://github.com/ImranR98/Obtainium/issues?q=sort%3Aupdated-desc+backup+downloaded+apks
* https://github.com/search?q=repo%3AImranR98%2FObtainium%20vendor%20dependencies&type=code
* https://github.com/ImranR98/Obtainium/issues?q=sort%3Aupdated-desc+vendored

**Comment by ebsangam** [comment] 2024-07-24 08:06
we need it, had to download same app 3 times

**Comment by DJCrashdummy** [comment] 2024-07-27 10:13
i'm not sure what the links in the "additional context" section should demonstrate... but IMHO this is at least related - if not a duplicate - of #1545.

**Comment by ImranR98** [comment] 2024-07-28 20:50
Similar enough to be considered a duplicate of #1545.

**Closed by ImranR98** 2024-07-28 20:50 UTC
Labels: enhancement, to check
