### ISSUE TITLE
Forbidden Error Adding Aurora Store Link and Root method Installation Errors

### ISSUE THREAD

**Issue by akashsriramganapathy** [ImranR98/Obtainium#1359] opened 2024-01-31 04:31 UTC
**Describe the bug**
Encountered multiple issues with Obtainium functionality.

**Issues Encountered:**

1. **Forbidden Error Adding Aurora Store Link:**
   - **Description:** While attempting to add the Aurora Store link in Obtainium, the system returns a "forbidden" error.
   - **To Reproduce:**
     1. Navigate to 'Add App' in Obtainium.
     2. Enter the link: `https://auroraoss.com/AuroraStore/Nightly/`.
     3. Observe the "forbidden" error.
   
2. **Root Method Installation Error:**
   - **Description:** When trying to install Obtainium using the root method on two different devices with distinct Android OS versions, the installation consistently ends with an error. A popup indicates that an unspecified error occurred.
   - **Additional Context:** Screenshots of the error messages during the installation process are provided.

**Screenshots and Logs**
![Screenshot_2024-01-31-09-50-30-086_dev imranr obtainium](https://github.com/ImranR98/Obtainium/assets/39720035/2efb0d1c-ca4e-41a3-af91-1fa5f2beb6e6)
![Screenshot_2024-01-31-09-49-57-442_dev imranr obtainium](https://github.com/ImranR98/Obtainium/assets/39720035/1f8f3b84-bdee-4a3a-8cbb-1c33b12f0c7e)

**Device Details:**
- **Device:** Mi 11X
- **OS:** Xiaomi.eu version 14.0.7.0 (Android 13)
- **Obtainium Version:** V1.0.1

**Comment by DwainZwerg** [comment] 2024-01-31 15:06
The first is a duplicate of #854 and https://github.com/ImranR98/Obtainium/issues/697#issuecomment-1715921713 … Fuck cloudflare

**Comment by ImranR98** [comment] 2024-02-01 23:55
Issue 1 is a duplicate of #854 as mentioned above. And from your description, it looks like issue 2 is a also duplicate of #1200.

**Closed by ImranR98** 2024-02-01 23:55 UTC
Labels: bug

**Comment by DwainZwerg** [comment] 2024-02-22 11:31
Hello @akashsriramganapathy ,
According to https://gitlab.com/AuroraOSS/AuroraStore/-/issues/1052#note_1778388859, the Aurora Store devs have fixed the problem. The download of AuroraStore should work normally again.
