### ISSUE TITLE
Handshake error in client

### ISSUE THREAD

**Issue by Sami32** [ImranR98/Obtainium#1663] opened 2024-06-10 10:01 UTC
An Handshake error is displayed for the first time (i mean that until yesterday it worked without error)  for the Conversations application from the Codeberg Git repo.

**To Reproduce**
1. Open Obtainium and leave it auto-update Conversations application in track-only mode
2. A Handshake error is displayed

**Screenshots and Logs**
![IMG_20240610_120230](https://github.com/ImranR98/Obtainium/assets/18471069/2b9438ed-aeb3-48e2-bf28-54040c3eef97)

**Please complete the following information:**
 - Device: Xiaomi Redmi Note 4
 - OS: Google Android 7.0
 - Obtainium Version: 1.1.10

**Additional context**
Only this link seem to recently (today) give this error:
https://codeberg.org/iNPUTmice/Conversations/tags

**Comment by ImranR98** [comment] 2024-06-15 05:46
Could you check if accessing that page works from your browser? Also could you check if the date/time settings on your phone are accurate?

**Comment by Sami32** [comment] 2024-06-15 07:57
Yes, date & time are set correctly on my smartphone, but as i said ONLY Conversations App is affected; that's said, it is the only one that i've using a Codeberg repo.

Yes, this Webpages display fine for me.

I should add that Obtainium overlay this error on the Conversations App page.

Codeberg only?

**Comment by Sami32** [comment] 2024-06-18 08:34
After having deleted this App it cannot be add anymore (Obtainium v. 1.1.11):

![IMG_20240618_094140](https://github.com/ImranR98/Obtainium/assets/18471069/9bad75eb-d3d7-421a-a367-37d22006453d)

**Comment by DarkCrypt** [comment] 2024-06-29 06:52
> After having deleted this App from Obtainium it cannot be added anymore (Obtainium v. 1.1.11)

Added app as track-only with v1.1.12.

**Comment by Sami32** [comment] 2024-06-29 20:44
Not with Android 7.0, installed or Track-only.

**Comment by Sami32** [comment] 2024-07-14 18:25
Two days ago these 2 Apps from F-Droid displayed this error as well but was working fine since months:

![IMG_20240711_102725](https://github.com/user-attachments/assets/e067ea77-c3cd-4ca5-bef2-492909ff182b)

**Comment by Sami32** [comment] 2024-07-17 15:21
And now with Obtainium version 1.1.14:

![IMG_20240716_095547](https://github.com/user-attachments/assets/3099793e-5f10-4b3c-bf75-7bc463725cc5)

**Comment by ImranR98** [comment] 2024-09-08 06:36
Realized this is a duplicate of #1458

**Closed by ImranR98** 2024-09-08 06:36 UTC
Labels: bug
