### ISSUE TITLE
No notifications

### ISSUE THREAD

**Issue by MatsG23** [ImranR98/Obtainium#87] opened 2022-11-02 17:33 UTC
I do not receive notifications from Obtainium although I setup a background update checking interval. I sometimes opened the app and saw available updates. I have never received a notification from Obtainium since I used it.
I have given Obtainium the A13 permission for sending notifications and removed the battery optimization (is that even needed?). The notifications work for other apps of which some do not use FCM but background notifications too.

App version: 0.6.4
Device info: Pixel 6a running GrapheneOS (based on AOSP 13)

**Comment by ImranR98** [comment] 2022-11-02 23:28
Interesting. When you opened the App, did you need to manually refresh or were the updates already there? In the latter case, it means that background checking does work, it just doesn't notify you. One thing to note is that Obtainium will only notify you of an update if it is new, meaning it did not already have an "update available" status - so if you swipe away the notification (or miss it somehow), it won't appear again. Is it possible you just missed it? Also keep in mind that the update interval is only approximate, Android ultimately decides when to do the task. I'm also on Graphene with Android 13, and notifications work fine for me.

Please try shortening the interval and see if that helps. Also, check your notification history (you'll need to enable this as it is off by default) and see if you get the "checking for updates" notification.

**Comment by ImranR98** [comment] 2022-11-03 19:04
By @bluefly000 on #92 (copying here as it looks like the same issue):

> Could you please add an option to keep Obtainium running in the background to check for updates?
> 
> I am using a Pixel6a running GrapheneOS and am having the same problem as mentioned in [#87](https://github.com/ImranR98/Obtainium/issues/87). Removing Obtainium from recent apps has stopped it from running in the background. Even without removing it from recent apps, using other apps, opening other profiles, etc. caused Obtainium to go into a suspended state and no longer check for updates in the background. Since there are no background update checks being done, there are no notifications. In my case, I only get notifications if I leave my smartphone for several hours after opening Obtainium.
> 
> I thought that adding this option would improve the reliability of the update checks in the background.

**Comment by ImranR98** [comment] 2022-11-03 19:07
@bluefly000 could you check my previous comment and check some of the things I mentioned (check your notification history, shorten interval, etc.)

I tried reproducing this today by clearing Obtainium from the task list, but I see it is still checking for updates.

The Android API being used for background tasks is supposed to work even after reboot, so this is surprising.

**Comment by bluefly000** [comment] 2022-11-04 08:17
I set the interval to 1 hour on 4 Android devices, Galaxy A21 SC-42A, Galaxy A22 SC-56B, Pixel4a and Pixel6a running GrapheneOS. Then, I checked my notification history 10 hours after clearing Obtainium from my task list. Battery optimization was disabled.

As a result, only the Galaxy A21 SC-42A was successfully checking for updates.
For the Pixel4a it worked fine for the first 6 or 7 hours, but after that I did not receive any update checking notifications.
Oddly enough, for Pixel 6a, the Checking for Updates notification came after 4 hours, even though the interval was set to 1 hour. Also, that is the only notification that was coming.
In the case of the Galaxy A22 SC-56B, there was no Checking for Updates notification. I opened Obtainium and checked the date and time of the Last Update Check and found that Obtainium was not running in the background.

**Comment by ImranR98** [comment] 2022-11-04 23:07
Very weird behaviour, especially since its inconsistent between devices. It looks like my phone is also running into this issue now for intervals above 1 hour.

Not sure what you meant by your last sentence there @bluefly000, there's no way to look at the last update check time in Obtainium (unless you're very quick). Each App does show the last update check time, but as soon as you open the app page it re-checks and so that time changes almost immediately.

Also, in the case of the Pixel 6a waiting 4 hours instead of 1 - was the screen off in the interim? If so, Android might have decided to wait until the phone was woken up (the interval time is like a suggestion, not exact, but I don't know if such a huge difference is normal).

It's possible this is due to https://github.com/fluttercommunity/flutter_workmanager/issues/415 (if so, I'm not sure how it can be resolved). Ultimately the only working option might be to use a foreground service for update checking, but that's such a bad solution that really shouldn't be necessary.

**Comment by ImranR98** [comment] 2022-11-04 23:08
In the meantime, I'll change the default interval to 1 hour and add a warning against changing it.

**Comment by ImranR98** [comment] 2022-11-04 23:21
Thanks! I'll try it out.

**Comment by ImranR98** [comment] 2022-11-05 20:16
I've switched to the AlarmManager plugin and everything seems to work. The only downside is that there's no way to make it wait for a network connection if there isn't one (previous plugin had this), so we just have to keep retrying every 15 minutes. It's probably fine (battery-life wise) since it only happens if the phone is awake (if asleep, it is woken up for normal update checks but not the 15-minute-later retries caused by network issues or rate limits - in those cases, we wait for wakeup).

I'll do a bit more testing today and release tomorrow. Have attached the APKs here in case you want to test it out too @MatsG23 @bluefly000. If you do, you might want to remove Obtainium from your Apps list so it doesn't try to downgrade to the current release (that would fail anyways).

[app-x86_64-release.zip](https://github.com/ImranR98/Obtainium/files/9944648/app-x86_64-release.zip)
[app-armeabi-v7a-release.zip](https://github.com/ImranR98/Obtainium/files/9944653/app-armeabi-v7a-release.zip)
[app-arm64-v8a-release.zip](https://github.com/ImranR98/Obtainium/files/9944654/app-arm64-v8a-release.zip)
[app-release.zip](https://github.com/ImranR98/Obtainium/files/9944655/app-release.zip)

**Comment by ImranR98** [comment] 2022-11-05 20:32
[app-x86_64-release.zip](https://github.com/ImranR98/Obtainium/files/9944672/app-x86_64-release.zip)
[app-armeabi-v7a-release.zip](https://github.com/ImranR98/Obtainium/files/9944673/app-armeabi-v7a-release.zip)
[app-arm64-v8a-release.zip](https://github.com/ImranR98/Obtainium/files/9944675/app-arm64-v8a-release.zip)
[app-release.zip](https://github.com/ImranR98/Obtainium/files/9944676/app-release.zip)

**Comment by ImranR98** [comment] 2022-11-06 03:36
[app-x86_64-release.zip](https://github.com/ImranR98/Obtainium/files/9945099/app-x86_64-release.zip)
[app-armeabi-v7a-release.zip](https://github.com/ImranR98/Obtainium/files/9945100/app-armeabi-v7a-release.zip)
[app-arm64-v8a-release.zip](https://github.com/ImranR98/Obtainium/files/9945101/app-arm64-v8a-release.zip)
[app-release.zip](https://github.com/ImranR98/Obtainium/files/9945102/app-release.zip)

**Comment by bluefly000** [comment] 2022-11-06 17:41
I tested on Pixel4a and Pixel6a. Notifications worked fine on both, but I got a Package parse error and could not add and update the app.

**Comment by bluefly000** [comment] 2022-11-06 18:18
I was able to add and install apps successfully with one version prior to the latest test version.

**Comment by ImranR98** [comment] 2022-11-06 18:35
The good news is the notifications issue is fixed. The package parse error is a separate thing that apparently got introduced in the last release (will look into it). In the meantime I've deleted the latest release since this bug breaks App adding.

**Comment by bluefly000** [comment] 2022-11-06 18:41
Sorry for the lack of clarity. I am not referring to version 0.6.6 that is giving me an error, but the version attached 15 hours ago in this issue. When I say it worked fine, I am referring to the version attached to the comment that is hidden as outdated.

**Comment by ImranR98** [comment] 2022-11-06 19:25
Fixed:
[app-x86_64-release.zip](https://github.com/ImranR98/Obtainium/files/9946647/app-x86_64-release.zip)
[app-armeabi-v7a-release.zip](https://github.com/ImranR98/Obtainium/files/9946648/app-armeabi-v7a-release.zip)
[app-arm64-v8a-release.zip](https://github.com/ImranR98/Obtainium/files/9946649/app-arm64-v8a-release.zip)
[app-release.zip](https://github.com/ImranR98/Obtainium/files/9946650/app-release.zip)

**Comment by ImranR98** [comment] 2022-11-06 22:18
Closing as fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.6.7-beta

**Closed by ImranR98** 2022-11-06 22:18 UTC
Labels: bug, high priority

**Comment by S7venLights** [comment] 2022-11-07 11:07
Nice work guys 🙌
