### ISSUE TITLE
Share Repo URL to Obtainium (or allow to scan it via QR code)

### ISSUE THREAD

**Issue by martin-braun** [ImranR98/Obtainium#423] opened 2023-04-04 21:54 UTC
Sometimes you have the repo open on the PC. Brave allows to show a QR code of the current URL, so it would be handy if the QR code could be scanned within Obtainium to import the repo URL.

Additionally, sharing an URL to Obtainium to add its app would be a compromise that could work in the meantime as well.

**Comment by fellinir** [comment] 2023-04-22 16:18
@martin-braun You can use a separate QR code scanner app which also does allow you to copy the decoded result, and then paste it in the "add app" screen in Obtainuim. It takes few taps, but at least the developer won't have to add new complexity and required permissions to consent just this single feature.

And with the recent Android versions if you share a link from any app you get the option to save it in the clipboard.

**Comment by martin-braun** [comment] 2023-04-22 16:56
@fellinir You have a fair point by saying it would add some complexity. I can see how it's beneficial to avoid such complexity to favor other issues. I want to keep this issue open for the sake of the possibility to share an URL to the app, which should be easy and quick to implement. This would reduce the required steps like copy-pasting.

**Comment by ImranR98** [comment] 2023-04-30 07:17
Just realized this is a duplicate of #109 (excepting the QR scanning function, which yes seems unnecessary).

**Closed by ImranR98** 2023-04-30 07:17 UTC
Labels: enhancement
