### ISSUE TITLE
uptodown: `Not Found` error when install FGO english apk

### ISSUE THREAD

**Issue by soredake** [ImranR98/Obtainium#1796] opened 2024-08-17 04:32 UTC
**Prerequisites**

**Describe the bug**

**To Reproduce**
1. Add https://fate-grand-order.en.uptodown.com/android to application list
2. Try to install it
3. `Not Found` error

**Screenshots and Logs**
![изображение](https://github.com/user-attachments/assets/51301017-4266-4aa0-92b2-b0089ee03b65)

<details>
<summary>Logs</summary>
2024-08-17 07:30:53.738: error: Not Found [Fate/Grand Order]
</details>

**Please complete the following information:**
 - Device: Motorola Edge 40
 - OS: Android 14
 - Obtainium Version: [v1.1.19](https://github.com/ImranR98/Obtainium/releases/tag/v1.1.19)

**Additional context**

**Comment by ImranR98** [comment] 2024-08-20 02:38
The 'Not Found' error will be fixed in the next release, but this app still doesn't work. Probably due to the same root cause as #1794 and #1795 (nothing to do with Uptodown specifically).

**Comment by ImranR98** [comment] 2024-08-20 03:15
https://github.com/ImranR98/Obtainium/releases/tag/v1.1.20

**Closed by ImranR98** 2024-08-20 03:15 UTC
Labels: bug, TODO, source-specific
