### ISSUE TITLE
share to add new app

### ISSUE THREAD

**Issue by weird-budy** [ImranR98/Obtainium#1901] opened 2024-10-11 12:11 UTC
I think it would be really good if you can share the link to obtainium from android's sharing menu to add new app. Like you are on github. you find an app and from Browser you share the link to obtainium and it's bing added. Unlike copy the link and than add the app

**Comment by DarkCrypt** [comment] 2024-10-11 23:39
Issue #109.

**Comment by ImranR98** [comment] 2024-10-12 17:36
Duplicate of #1901

**Closed by ImranR98** 2024-10-12 17:36 UTC
Labels: enhancement, to check
