### ISSUE TITLE
[Feature Request]: Adaptive/Themed Icon for A12.1

### ISSUE THREAD

**Issue by rcarteraz** [ImranR98/Obtainium#345] opened 2023-03-03 22:26 UTC
Curious... I have an Oneplus Nord N200 that I'm running a LineageOS fork called [LMODroid](https://libremobileos.com) that's based on A12.1. The rom supports themed icons, like A13 has. Interestingly, I installed Bitwarden on it and unlike Obtainium, it immediately changed to match the theme when added to the home screen. Researching this a little further, as It'd be nice to have this functionality for Obtainium too (on A12.1, as I know it's supported on A13 as I have it on my Pixel). Taking a look at Bitwarden's setup, and there's a couple difference from Obtainium, which you can see [here](https://github.com/bitwarden/mobile/commit/2deab59b35cb1a44c34e152f9da07d1110a0dfc2).

So, as I started this, I'm curious.. Is this something that might be possible to implement for Obtainium? Low priority of course.

**Comment by ImranR98** [comment] 2023-03-04 01:38
I don't see any obvious reason it wouldn't work, but tried adding an optional file like Bitwarden has. Try this APK and let me know how it goes: 
[app-x86_64-release.zip](https://github.com/ImranR98/Obtainium/files/10887203/app-x86_64-release.zip)
[app-release.zip](https://github.com/ImranR98/Obtainium/files/10887204/app-release.zip)
[app-arm64-v8a-release.zip](https://github.com/ImranR98/Obtainium/files/10887206/app-arm64-v8a-release.zip)
[app-armeabi-v7a-release.zip](https://github.com/ImranR98/Obtainium/files/10887205/app-armeabi-v7a-release.zip)

The only other difference I see is that Bitwarden uses vector shapes in an XML file instead of PNG images. If that's the cause, it's not worth supporting as I have no clue how to convert the existing icon (esp. since it isn't just a shape). Especially since this works on Android 13 (so we know LMO's implementation isn't 100% identical to the official one).

**Comment by ImranR98** [comment] 2023-03-04 04:06
Took a bit of messing around in Inkscape, but logos/icons are "supposed" to be vectors anyways and this will reduce duplicate images. Hopefully it works now, if not I'm out of ideas: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.7-beta

**Comment by ImranR98** [comment] 2023-03-04 04:37
https://github.com/ImranR98/Obtainium/releases/tag/v0.11.7-beta

**Comment by ImranR98** [comment] 2023-03-04 23:31
I'm going to assume this worked and close the issue. Let me know if it didn't so I can close as not planned instead.

**Closed by ImranR98** 2023-03-04 23:31 UTC
Labels: enhancement, needs follow up
