### ISSUE TITLE
Auto update feature

### ISSUE THREAD

**Issue by JohnBetaro** [ImranR98/Obtainium#127] opened 2022-11-25 10:59 UTC
Android 12 has a mechanism to allow an app that installed an application to update it in the background, you just have to click update and it will download an install without permission but the client needs to be updated to support it.

Some of the other F-Droid clients, like Droid-ify have, I suggest you take a look.
And also Aurora Store does have this feature.

This all works without any extensions like fdroid-privileged-extension or aurora services.

Thank you for your time.

**Comment by ImranR98** [comment] 2022-11-25 16:29
Duplicate of #25

**Closed by ImranR98** 2022-11-25 16:29 UTC
