### ISSUE TITLE
Citra Nightly Update is stuck at version 2006

### ISSUE THREAD

**Issue by spider2MW** [ImranR98/Obtainium#1156] opened 2023-12-14 12:54 UTC
**Describe the bug**
Citra Nightly Update is stuck at version 2006

**To Reproduce**
Try to update Citra in Obtainium, latest version there is 2006, on Github 205x

**Screenshots and Logs**
![289317315-ce47a71a-e72c-4569-b387-8759b8e45fb3](https://github.com/ImranR98/Obtainium/assets/153829405/ab8ef0d1-3865-4452-b777-82357b6ce9f7)
![289317308-3b5c9d2a-c542-4981-b577-925cd53c703b](https://github.com/ImranR98/Obtainium/assets/153829405/0b908403-44e1-47d8-bf34-438559f66ef5)
![289317274-58a1148e-6b03-4b01-a113-267db3dd5f78](https://github.com/ImranR98/Obtainium/assets/153829405/d6fe5ba3-ce47-42a7-9afd-a559dcbd4891)

**Please complete the following information:**
Poco F5 Pro, Android 13, latest version of Obtainium

**Additional context**
As metioned in the Discussions, the issue is maybe that from Citra 2007 on every apk is zipped. Is it possible for Obtainium to handle these zip files?

**Comment by ThreeDeeJay** [comment] 2023-12-15 00:32
Known issue. Relevant (and maybe even useful) info: https://github.com/ImranR98/Obtainium/issues/983#issuecomment-1853391143

**Comment by ImranR98** [comment] 2023-12-15 11:47
Yes, duplicate of #983

**Closed by ImranR98** 2023-12-15 11:47 UTC
Labels: bug, to check
