### ISSUE TITLE
Can't add Telegram

### ISSUE THREAD

**Issue by BabyOilJohnson** [ImranR98/Obtainium#370] opened 2023-03-19 13:21 UTC
I can't add telegram, show this error.
![Screenshot_20230319-183615](https://user-images.githubusercontent.com/101601874/226177860-09911bdc-9dc0-4db9-afef-e8572513bc60.png)

**Comment by ImranR98** [comment] 2023-03-19 15:59
Can't reproduce this on my end. But it looks like an issue with your connection. Does this happen on repeated attempts? Does telegram.org load in your browser? What about https://t.me/s/TAndroidAPK ?

**Comment by BabyOilJohnson** [comment] 2023-03-19 16:37
> Does this happen on repeated attempts?

Yes

> Does telegram.org load in your browser?

Yeah, without problem.

> What about https://t.me/s/TAndroidAPK ?

Still same issue.

**Comment by ImranR98** [comment] 2023-03-19 16:41
What Android version are you on?

**Comment by BabyOilJohnson** [comment] 2023-03-19 16:43
11

**Comment by ImranR98** [comment] 2023-03-19 18:06
Works on my Android 11 emulator too. Can't think of why this wouldn't work even if other sources do :|

**Comment by ImranR98** [comment] 2023-03-19 18:06
Does this happen right after clicking the Add button or some time during the download?

**Comment by BabyOilJohnson** [comment] 2023-03-19 18:09
Right after clicking the add button.

**Comment by ImranR98** [comment] 2023-03-19 18:11
Weird. I guess this is blocked for now until I can get it to happen on my device. In the meantime please try things like switching to a separate network, reinstalling Obtainium, etc. to see if anything helps.

**Comment by BabyOilJohnson** [comment] 2023-03-20 09:05
I tried on another network and it's work. I think the was error was caused by ISP.

**Comment by tazihad** [comment] 2023-03-20 10:03
I also can't add the source. It saya "No suitable release" in android 13

**Comment by BabyOilJohnson** [comment] 2023-03-20 10:17
> I also can't add the source. It saya "No suitable release" in android 13

I also got the same "no suitable release", when I tried with this url https://t.me/s/TAndroidAPK

**Comment by ImranR98** [comment] 2023-03-20 11:19
The only valid url is telegram.org to get the telegram mobile app. This does not support getting apps from individual telegram channels (there's already an existing issue for that but it's going to be more complicated).

Since the network problem is figured out, I'll close this.

**Closed by ImranR98** 2023-03-20 11:19 UTC
Labels: bug, needs follow up

**Comment by ImranR98** [comment] 2023-03-20 11:21
The only url that will work is telegram.org to get the telegram mobile app, you can't use individual telegram channels as app sources yet - that's a separate issue and is more complicated.

Since the network problem is fixed i'll close this issue.
