### ISSUE TITLE
It is recommended to add the functions of pausing download and canceling download

### ISSUE THREAD

**Issue by nichousha123** [ImranR98/Obtainium#1626] opened 2024-05-16 05:46 UTC
The download cannot be paused after it starts. After half the download, I regret it and cannot cancel it

**Comment by ImranR98** [comment] 2024-05-16 05:48
You already opened this issue and it was closed as a duplicate of #950. That issue is the same as this one and already exists - it is older.

**Closed by ImranR98** 2024-05-16 05:48 UTC
Labels: enhancement, to check
