### ISSUE TITLE
Allow discussions

### ISSUE THREAD

**Issue by jcperil** [ImranR98/Obtainium#515] opened 2023-04-30 11:00 UTC
Can you unlock the Discussions feature for this GitHub Repo? i.e. https://github.com/ImranR98/Obtainium/discussions

This will allow us to ask general questions that are neither bugs nor feature requests.

**Comment by ImranR98** [comment] 2023-04-30 18:38
Duplicate of #285 but I forgot about it before. Unlocked: https://github.com/ImranR98/Obtainium/discussions

**Closed by ImranR98** 2023-04-30 18:38 UTC
