### ISSUE TITLE
Add import link from sharing menu

### ISSUE THREAD

**Issue by NripPrajapat** [ImranR98/Obtainium#1991] opened 2024-11-25 01:24 UTC
Whenever I copy a link, it should simply provide an option to add it to Obtainium,
In clipboard strip or Sharing menu.

**Comment by DarkCrypt** [comment] 2024-11-25 03:38
Duplicate of #109.

**Closed** 2024-11-26 16:15 UTC
Labels: enhancement, to check

**Comment by NripPrajapat** [comment] 2024-11-27 01:14
It is simply the best and simpler way to add a link and save a user's time, why won't you add this?
It'll save time, don't you think it will?

**Comment by ImranR98** [comment] 2024-11-27 01:31
@NripPrajapat yes, there is already an open issue for this
