### ISSUE TITLE
Include application icon for track-only applications.

### ISSUE THREAD

**Issue by rufusprice** [ImranR98/Obtainium#1388] opened 2024-02-11 07:52 UTC
**Describe the feature**
Show application icons for track-only apps.

**Describe alternatives you've considered (if applicable)**
No known alternative.

**Additional context**
For installed apps, the app icons show in the Obtainium app list. For track only apps, there is no icon displayed. If the app download is necessary for the icon to be displayed, an alternative could be letting the user load a custom icon as part of the Obtainium app settings.

**Comment by ImranR98** [comment] 2024-02-18 23:44
Duplicate of #611 (also related to #294).

**Closed by ImranR98** 2024-02-18 23:44 UTC
Labels: enhancement, to check
