### ISSUE TITLE
Search inside of third party F-Droid repo

### ISSUE THREAD

**Issue by Sir-Photch** [ImranR98/Obtainium#770] opened 2023-08-13 02:23 UTC
Currently, it is possible to add a third party f-droid repo. This requires the user to know the app name though. This might not always be applicable though, especially with beta builds that are also present in the repository.

It is kind of cumbersome to have to specify the name of the app to download. Would it be possible to change the behavior in such a way that one could search inside of the third party repo?

**Comment by ImranR98** [comment] 2024-03-23 04:13
Didn't realize #995 was a duplicate of this. Closing (implemented).

**Closed by ImranR98** 2024-03-23 04:13 UTC
Labels: enhancement
