### ISSUE TITLE
Tv version

### ISSUE THREAD

**Issue by KUKARAF** [ImranR98/Obtainium#1020] opened 2023-10-17 21:16 UTC
**Describe the feature**
APK Version for android tv 

n/a

**Comment by ImranR98** [comment] 2023-10-18 00:30
Duplicate of #281

**Closed by ImranR98** 2023-10-18 00:30 UTC
Labels: enhancement

**Comment by tazztone** [comment] 2024-12-10 22:01
ye would be nice.
wanted to install smarttube with it. somehow it broke my remote control navigation (buttons were no longer doing what they're supposed to do) and i had to reboot the tv box ( leap s3+). happened many times. not sure what about obtainium could cause this
