### ISSUE TITLE
App not responding and crashes when installing updates

### ISSUE THREAD

**Issue by Ketsuyumi** [ImranR98/Obtainium#1410] opened 2024-02-19 17:24 UTC
**Prerequisites**

 When installing am app using Shizuku method, I get multiple messages saying App is not responding, and I get 2 options, wait or close. The problem is it keeps popping up when it's done getting the file and it's installing the new version. **

1. Go to 'apps.'
2. Tap on 'any app's update'
3. App is not responding

 - Device: -- [Galaxy S23 Ultra] 
 - OS: -- [One UI 6.0] -
 - Obtainium Version: -- [1.0.3]

How often it happens
 It happened on each version I ever had, since I installed the app. At first, I thought it's normal, but my friend said he doesn't have this problem, so it must be a bug.

https://github.com/ImranR98/Obtainium/assets/98485150/a9c2ee31-2ec8-42f3-891c-d2a02d3cd0ce

**Comment by ImranR98** [comment] 2024-02-25 07:43
Duplicate of #1294

**Closed by ImranR98** 2024-02-25 07:43 UTC
Labels: bug, to check
