### ISSUE TITLE
Extract from github action

### ISSUE THREAD

**Issue by kaorlol** [ImranR98/Obtainium#1599] opened 2024-05-03 01:27 UTC
**Describe the feature**
Add an app through a github action, for example, Dantotsu's pretest apk is released in the artifacts of the action that is ran. Yes it is posted in telegram and discord but discord probably wouldnt be possible to add to this and not every pretest apk is released in telegram so it would be nice to have this feature built into Obtainium. Ive already made one using gh workflows with golang (https://github.com/kaorlol/obtainium-artifact-downloader) but it would probably be better to be built into this app.

(this doesnt only apply to Dantotsu, ive seen many other apps do this)

**Describe alternatives you've considered (if applicable)**
Only other alternative was doing it this way: https://github.com/kaorlol/obtainium-artifact-downloader

**Additional context**

You should probably make it a different page in the app and also have its on github pat token, i found that 10 seconds it probably the best because you can have up to around 10 actions being checked every 10 seconds, maybe a little more. (without being ratelimited)

Also you can check out my code since go is pretty readable and it uses the github apk so you can see how i did it and you could make it work in Kotlin or wtv lang you use)

**Comment by kaorlol** [comment] 2024-05-03 01:28
If you have any questions I'll be happy to answer them. And concerns.

**Comment by ImranR98** [comment] 2024-05-03 01:30
Duplicate of #102

**Closed by ImranR98** 2024-05-03 01:30 UTC
Labels: enhancement, to check

**Comment by kaorlol** [comment] 2024-05-03 01:35
oh sorry i checked through a bunch and never saw that issue
