### ISSUE TITLE
Please add Support for App-Package Name Configuration

### ISSUE THREAD

**Issue by STAINCABLER360** [ImranR98/Obtainium#1087] opened 2023-11-13 21:35 UTC
Some apps, that I want to install from GitHub, get in Obtainium a different package name than it is.
For example, in Obtainum the package name is listed as `app.package.githubuser`, but on my phone, after installation, the package name is `com.appname.app`.
Unfortunately, I can't get updates for these apps via Obtainium, because the package names don't match :/

My suggestion would be that you either try to intercept the package name during installation or that you can change it in the source configuration.

Thank you for your great work with Obtainium and greetings.

**Comment by ImranR98** [comment] 2023-11-13 21:38
Could you give me an example of an app where this happens? I don't see how it could happen given that we extract app IDs directly from the APK or from sources where the ID is guaranteed to match. The only situation where this could happen is if we are trying to extract the app ID from a github repo and aren't doing so correctly.

**Comment by ImranR98** [comment] 2023-11-13 23:46
In that last case, you can disable the option that says "infer App ID from source code".

**Comment by kinghat** [comment] 2023-11-16 21:38
another example: https://github.com/AgoraDesk-LocalMonero/agoradesk-app-foss/releases/tag/v1.1.14, when you have the repo added and i have a filter apk regex of: `co.localmonero.app-foss_` for specifically trying to get: https://github.com/AgoraDesk-LocalMonero/agoradesk-app-foss/releases/download/v1.1.14/co.localmonero.app-foss_110.apk it adds the repo but says i have none installed:

![image](https://github.com/ImranR98/Obtainium/assets/16073360/5581a4e5-d2b0-41e8-b935-dac7ea7a980c)

and the locally installed app id:

![image](https://github.com/ImranR98/Obtainium/assets/16073360/d69e1015-440d-49e4-ad7d-2c6dd5dc5623)

**Comment by ImranR98** [comment] 2023-11-16 22:04
That's because there are 2 different IDs depending on which APK you pick. From the OS point of view those are 2 separatr apps - you can decide which one you want and only pick that apk.

**Comment by ImranR98** [comment] 2023-11-16 22:05
Please make sure the APK variant you select when adding the app is the one you actually want.

**Comment by kinghat** [comment] 2023-11-16 23:30
> Please make sure the APK variant you select when adding the app is the one you actually want.

im not sure what you mean. isnt that what im doing by setting the apk regex of `co.localmonero.app-foss_`? theres only one that matches that in the release assets.

**Comment by ImranR98** [comment] 2023-11-16 23:38
You have to do it when adding the app for the first time because that's when the id gets set.

**Comment by kinghat** [comment] 2023-11-16 23:47
> You have to do it when adding the app for the first time because that's when the id gets set.

i removed the app in obtainium and started over adding the repo again, still used the apk regex, and turned off the determine the app id from source option and i think that worked.

**Comment by ImranR98** [comment] 2023-11-17 06:14
Closing - expected behaviour.

**Closed by ImranR98** 2023-11-17 06:14 UTC
Labels: bug
