### ISSUE TITLE
Export uses wrong encoding

### ISSUE THREAD

**Issue by ncaat** [ImranR98/Obtainium#888] opened 2023-09-13 16:47 UTC
**Describe the bug**
Export uses the wrong encoding
**To Reproduce**
1. Add an app that uses emojis in the changelog (e.g., https://github.com/HeCodes2Much/mLauncher)
2. Export
3. See error

**Additional context**
🐛 (U+1F41B) is displayed as `0x3D1B` in the json file.
The UTF-16 encoding of the emoji is `0xD83D 0xDC1B` so something seems to have gone wrong.
The [`writeAsStringSync`](https://api.flutter.dev/flutter/dart-io/File/writeAsStringSync.html) method that was used prior to this uses UTF-8 by default.
https://github.com/ImranR98/Obtainium/blob/17b5604f2a3c01a63f082736d5c598f847323acb/lib/providers/apps_provider.dart#L1131-L1135

**Comment by ImranR98** [comment] 2023-09-13 16:49
Duplicate of #887

**Closed by ImranR98** 2023-09-13 16:49 UTC
Labels: bug, to check
