### ISSUE TITLE
No update found at GitLab Release provider

### ISSUE THREAD

**Issue by mjdNjhNJ** [ImranR98/Obtainium#1380] opened 2024-02-08 12:09 UTC
**Describe the bug**
[AuroraOSS/AuroraStore](https://gitlab.com/AuroraOSS/AuroraStore/-/releases/4.4.0) got an update today and Obtainium is not showing that the new version is available.

**To Reproduce**
1. Add [AuroraOSS/AuroraStore GitLab Release](https://gitlab.com/AuroraOSS/AuroraStore/-/releases/) URL to the Obtainium
2. Wait for a new version

**Please complete the following information:**
 - Device: Pixel 7a
 - OS: GrapheneOS (Android 14)
 - Obtainium Version: 1.0.2

**Additional context**
Can't update the app from version 4.3.5 to 4.4.0. Maybe the problem is that from AuroraStore 4.4.0 they are publishing the APK as "Packages" instead in attachements?

**Comment by ImranR98** [comment] 2024-02-08 18:05
@ThreeDeeJay is right - this likely a duplicate of the other Aurora issues.

**Closed by ImranR98** 2024-02-08 18:05 UTC
Labels: bug, to check

**Comment by DwainZwerg** [comment] 2024-02-22 11:31
Hello @mjdNjhNJ ,
According to https://gitlab.com/AuroraOSS/AuroraStore/-/issues/1052#note_1778388859, the Aurora Store devs have fixed the problem. The download of AuroraStore should work normally again.

**Comment by mjdNjhNJ** [comment] 2024-02-22 11:36
@DwainZwerg I have updated the Aurora Store manually. Now Obtanium shows there is a new update available. However the update it's trying to install is Aurora Store with version of 4.3.5. The manually installed one is of version 4.4.1. Error message says: "Cannot install an older version of an App [Aurora Store]" which makes sense. I don't know if this is an Obtainium issue or the fact I mentioned while creating this issue.

**Comment by DwainZwerg** [comment] 2024-02-23 15:48
Hello @jayb-g ,
do you use GitLab-Token? If not, use it. If you are using it and Obtainium does not show you the update, you should delete the app from Obtainium and add it again. If it still doesn't work, it's an unknown behaviour, and I'm not sure if it's auroraoss.com's side or Obtainium. We are also in the process of adding a general feature to better retrieve updates from sites that are protected by Cloudflare (https://github.com/ImranR98/Obtainium/pull/1411).
#920 should actually have nothing to do with this, because it's about a problem with the F-Droid-API.
@ImranR98 @Disqu3-mirOir-qt for acknowledgement.

**Comment by jayb-g** [comment] 2024-02-23 16:18
@mjdNjhNJ its resolved with the token
