### ISSUE TITLE
Sourceforge OpenCamera source broken

### ISSUE THREAD

**Issue by S7venLights** [ImranR98/Obtainium#391] opened 2023-03-27 06:39 UTC
https://sourceforge.net/projects/opencamera

is in my obtainium but it's not detecting the latest update.

**Comment by ImranR98** [comment] 2023-03-27 21:47
Can't reproduce this on my end. Do you see any error message?

**Comment by S7venLights** [comment] 2023-03-28 08:39
Okay so I was on 1.50.1 and it wasn't notifying me to install 1.51.1
So I tried resetting the install status in obtanium then told obtaininm to download OpenC again.
Then I got a conflicting package error.
I then uninstalled it and reinstalled in in obtainium and it installed the latest version fine.
So you might want to test why it didn't notify for the latest version but otherwise you can close this issue.

**Comment by ImranR98** [comment] 2023-03-29 00:46
I've simplified some of the version detection code, and made it so that apps that can't use version detection automatically fallback to "no version detection". Not sure if it will solve your problem, but since the version detection code is kind of messy, it could use some testing either way. I'll be using this version for a while, attaching it here in case you're interested in testing it as well.

[app-x86_64-release.zip](https://github.com/ImranR98/Obtainium/files/11095460/app-x86_64-release.zip)
[app-release.zip](https://github.com/ImranR98/Obtainium/files/11095461/app-release.zip)
[app-armeabi-v7a-release.zip](https://github.com/ImranR98/Obtainium/files/11095465/app-armeabi-v7a-release.zip)
[app-arm64-v8a-release.zip](https://github.com/ImranR98/Obtainium/files/11095466/app-arm64-v8a-release.zip)

**Comment by ImranR98** [comment] 2023-03-29 09:55
Found a bug, will attach a new apk.

**Comment by ImranR98** [comment] 2023-03-29 15:03
Significantly cleaned up version detection. It is now fully automatic - no need to pick "no version detection" etc. Might have bugs.

[app-x86_64-release.zip](https://github.com/ImranR98/Obtainium/files/11102308/app-x86_64-release.zip)
[app-release.zip](https://github.com/ImranR98/Obtainium/files/11102310/app-release.zip)
[app-armeabi-v7a-release.zip](https://github.com/ImranR98/Obtainium/files/11102316/app-armeabi-v7a-release.zip)
[app-arm64-v8a-release.zip](https://github.com/ImranR98/Obtainium/files/11102326/app-arm64-v8a-release.zip)

**Comment by ImranR98** [comment] 2023-03-30 03:08
Version above seems to work. Made a few more code-side changes (nothing significant). If there's no bugs, I'll release tomorrow and close this issue as it hopefully was either a one-time glitch or fixed by these changes.

[app-x86_64-release.zip](https://github.com/ImranR98/Obtainium/files/11107343/app-x86_64-release.zip)
[app-release.zip](https://github.com/ImranR98/Obtainium/files/11107345/app-release.zip)
[app-armeabi-v7a-release.zip](https://github.com/ImranR98/Obtainium/files/11107346/app-armeabi-v7a-release.zip)
[app-arm64-v8a-release.zip](https://github.com/ImranR98/Obtainium/files/11107348/app-arm64-v8a-release.zip)

**Comment by ImranR98** [comment] 2023-03-30 21:51
Released: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.16-beta

Ignore previous comments with out of date APKs.

Closing this issue. Not sure if this release would have prevented your issue, but probably would. Feel free to re-open if needed.

**Closed by ImranR98** 2023-03-30 21:51 UTC
Labels: bug
