### ISSUE TITLE
F-Droid reproducible build failed

### ISSUE THREAD

**Issue by linsui** [ImranR98/Obtainium#1702] opened 2024-06-30 08:25 UTC
**Prerequisites**

**Describe the bug**

https://gitlab.com/linsui/fdroiddata/-/jobs/7224096941 1.1.13 reproducible build failed. The content of the apk is identical but the zip metadata is different. I checked 1.1.11 again and I can still rebuild the apk.

**To Reproduce**

**Screenshots and Logs**

[out.txt](https://github.com/user-attachments/files/16043720/out.txt)

**Please complete the following information:**
 - Device: 
 - OS: 
 - Obtainium Version: 

**Additional context**

**Comment by ImranR98** [comment] 2024-06-30 14:54
Hmm. Do you have any ideas? I haven't changed anything that should affect this afaik.

**Comment by linsui** [comment] 2024-06-30 15:49
I have no idea. Can you try rebuilding 1.1.11 and check if the apk is identical to the old one?

**Comment by ImranR98** [comment] 2024-06-30 17:19
[app-arm64-v8a-release.zip](https://github.com/user-attachments/files/16045521/app-arm64-v8a-release.zip)

**Comment by ImranR98** [comment] 2024-06-30 17:22
Looks like the file hashes are not identical. I built this through GitHub actions so something might be different there.

**Comment by ImranR98** [comment] 2024-06-30 17:27
Do you know what zip metadata is different? I'm assuming the APK signature is okay since Android did not complain when the version updated.

**Comment by linsui** [comment] 2024-06-30 17:54
This is the diff between your new build and old build of 1.1.11. 
[diff.txt](https://github.com/user-attachments/files/16045612/diff.txt)

The out.txt above is the diff between your build of 1.1.13 and our build.

**Comment by ImranR98** [comment] 2024-06-30 19:15
Lol, I have no idea how to interpret these.

**Comment by licaon-kter** [comment] 2024-07-01 05:23
That's how these look like when hitting aligning issues, iirc.


@linsui, none of the 4, 16, 64 values helped?

**Comment by linsui** [comment] 2024-07-01 05:25
I didn't try. We shouldn't need to run zipalign again unless we modify the apk.

**Comment by licaon-kter** [comment] 2024-07-01 05:47
Who is we? We are not modifying anything on purpose, we try to keep up with the "ever evolving" tooling that changes that, right?

**Comment by licaon-kter** [comment] 2024-07-01 11:14
tried 4 (not need as it's already 4), 16 and 64 to zipalign from Debian, but not helpful :crying_cat_face:

**Comment by ldeso** [comment] 2024-07-01 12:51
This may be caused by the [Dependency Info Block](https://developer.android.com/build/dependencies#dependency-info-play), an encrypted proprietary blob from Google that is added to APK and AAB files by default and that is [not reproductible](https://issuetracker.google.com/issues/268071369). This causes changes the APK signature block to be different on every build even though the signature certificate remains the same.

You could try to remove this blob by adding the following to the file build.gradle:

```java
android {
    // …

    dependenciesInfo {
        includeInApk false
        includeInBundle false
    }
}
```

**Comment by licaon-kter** [comment] 2024-07-01 14:14
worth a try

**Comment by linsui** [comment] 2024-07-01 16:31
The signature is not same.

**Comment by linsui** [comment] 2024-07-03 15:43
Can you try signing the apk with apksigner from build-tools 34 or older?

**Comment by licaon-kter** [comment] 2024-07-05 15:44
@ImranR98 or better yet, adjust https://github.com/ImranR98/Obtainium/blob/v1.1.13/.github/workflows/release.yml#L75 to say `apksigner sign --alignment-preserved true  ...`

ref: https://gitlab.com/fdroid/fdroiddata/-/issues/3299#note_1985568674

**Comment by licaon-kter** [comment] 2024-07-09 12:42
Based on the docs here: https://github.com/obfusk/apksigcopier#what-about-signatures-made-by-apksigner-from-build-tools--3500-rc1

I've updated the recipe instead: https://gitlab.com/fdroid/fdroiddata/-/commit/b4ad3d5c41cd95caa67d9f4158334209f4cc6601

feel free to star the Google issue https://issuetracker.google.com/issues/351408623

/close this

**Closed** 2024-07-15 01:15 UTC
Labels: bug, high priority
