### ISSUE TITLE
Null (instead of the App informations)

### ISSUE THREAD

**Issue by Sami32** [ImranR98/Obtainium#1425] opened 2024-02-26 13:08 UTC
![Screenshot_2024-02-26-13-51-26-939_dev imranr obtainium](https://github.com/ImranR98/Obtainium/assets/18471069/e9c05399-73a4-48e2-a324-2815d710a0f2)

**Describe the bug**
Sometimes clicking on a non installed App in track-only mode just display "null".

**To Reproduce**
1. Launch Obtainium
2. Click on a non installed App in track-only mode
3. See error --> null
4. Clicking a new time on this same App display normally.

**Please complete the following information:**
 - Device: Xiaomi Redmi Note 4
 - OS: Google Android 7.0
 - Obtainium Version: 1.0.3

**Additional context**
I only saw this error appear with App not installed,  in track-only mode.
It seem only appear after the launch of Obtainium?

**Comment by ImranR98** [comment] 2024-02-26 16:13
The changelog is taken from the repo's releases page. If the repo has no releases (and it is a track-only app), [we use tags instead](https://github.com/ImranR98/Obtainium/blob/main/lib/app_sources/github.dart#L418) (in which case GitHub does not provide a changelog).

For your repo, there are no releases so we wouldn't expect to see a changelog: https://github.com/cmeng-git/atalk-android/releases. So just to clarify, the lack of a changelog is not a bug.

That said, we still should not see 'null' - it should just link to the releases page instead (so this is still a [bug](https://github.com/ImranR98/Obtainium/blob/main/lib/app_sources/github.dart#L404)).

**Comment by SonicWarrior1** [comment] 2024-02-27 17:01
Hey i can work on this issue , it looks pretty simple we can just show "No Changelog" text or just an empty string. So can u assign this issue to me .

**Comment by ImranR98** [comment] 2024-02-27 17:10
> we can just show "No Changelog" text or just an empty string.

See the previous comment. When changelog is `null`, the user is redirected to the main GitHub releases page (because sometimes the API might not return any changelog even though the releases page does have one - there was another issue about this). The bug here is that instead of returning `null`, track-only apps without changelogs return `"null"` (a string that says null).

I've already made the fix on my branch (a one line change on this line: https://github.com/ImranR98/Obtainium/blob/main/lib/app_sources/github.dart#L403)

**Comment by Sami32** [comment] 2024-02-28 11:23
Not only "Null" value display is a bug but also the fact that the first it only display this kind of page and next time an other one:

![Screenshot_2024-02-28-12-19-28-292_dev imranr obtainium](https://github.com/ImranR98/Obtainium/assets/18471069/9227584f-84a4-4e41-aaa6-1801f11d2431)
![Screenshot_2024-02-28-12-20-17-293_dev imranr obtainium](https://github.com/ImranR98/Obtainium/assets/18471069/3a2cac71-60d6-4dec-b618-067cc6845baf)

Shouldn't it be consistent? Or did i missed something?

**Comment by ImranR98** [comment] 2024-03-01 00:25
You get the changelogs when you tap the date, you get the other page when you tap anywhere else on the row.

**Comment by ImranR98** [comment] 2024-03-02 03:02
https://github.com/ImranR98/Obtainium/releases/tag/v1.0.4

**Closed by ImranR98** 2024-03-02 03:02 UTC
Labels: bug, TODO, UI
