### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [ImranR98/Obtainium#30] opened 2022-09-24 12:18 UTC
Hi,

Since this app is FLOSS itself, it could be a good idea to add it to F-Droid, so that people knows about it and use it.

What do you think?

**Comment by ImranR98** [comment] 2022-09-24 17:11
If it was on F-Droid, Obtainium would not be able to update itself (because F-Droid apps have their own signature). That's fine, but it means there would have to be a separate build of the which does not automatically include Obtainium as a tracked App out of the box (because then it would try to update itself from GitHub and fail). Right now that's hardcoded but can probably be changed to be optional based on a build option or something.

But is not a priority especially since part of the motivation for this app was to move away from F-Droid. Will leave the issue open but may not get around to it anytime soon.

**Comment by sbstn87** [comment] 2022-10-13 19:36
Perhaps a separate repo that can be added to F-Droid would be a solution for now?

**Comment by rollingmoai** [comment] 2023-02-09 14:09
> Perhaps a separate repo that can be added to F-Droid would be a solution for now?

Obtainium is now on the IzzyOnDroid repo: https://apt.izzysoft.de/fdroid/index/apk/dev.imranr.obtainium

**Comment by ImranR98** [comment] 2023-02-11 01:21
@rollingmoai does this require any maintenance when the app is updated? Or does it automatically grab everything from GitHub?

**Comment by rollingmoai** [comment] 2023-02-11 01:35
It automatically grabs everything from GitHub, so you don't have to worry about it.

**Comment by ImranR98** [comment] 2023-02-11 01:36
Great, thanks!

**Comment by licaon-kter** [comment] 2023-03-17 09:00
@ImranR98 
>  (because F-Droid apps have their own signature)

That's not a problem if the app is reproducible... but

> Obtainium would not be able to update itself 

F-Droid would like this to be opt-in :)

**Comment by licaon-kter** [comment] 2023-05-19 17:10
@momobobe the repro idea is _"the app is reproducible and F-Droid hosts the APK from the developer AFTER it verifies that reproducibilty"_

An in-app updater bypasses any verification, so users that put their trust in F-Droid get "lied" (strong word, bare with me) that all the app updates were verified.

FYI, almost every F-Droid cycle there's a repro app that fails verification.

So, to make things clear, an opt-in app updater is okay, as long as the user turns it on and gets informed that then the update comes straight from the developer.

**Comment by inson1** [comment] 2023-10-19 00:24
It there any upate?

**Comment by linsui** [comment] 2023-12-17 08:52
IIUC, we need to have the fdroid flavor build and uploaded somewhere.

**Comment by ClockGen** [comment] 2024-01-20 00:21
@ImranR98 can you please build and attach fdroid flavor builds as well to regular ones when you upload new releases?

**Comment by ImranR98** [comment] 2024-01-20 01:48
@ClockGen I can't build fdroid flavours (i mean i can build it, but it wouldn't actually be signed by f-droid).

**Comment by ClockGen** [comment] 2024-01-20 02:06
@ImranR98 Weird, I thought that F-Droid maintainers are currently waiting for you to publish f-droid flavor apks so they can set up reproducible builds (so apks signed by you are published in f-droid), with the only changes that f-droid flavor has, is that the package id is different and obtainium doesn't add itself to app list automatically https://github.com/ImranR98/Obtainium/pull/236.

**Comment by ImranR98** [comment] 2024-01-20 03:58
Thanks for the links, I forgot where the issue was. I'll include F-Droid builds with the next release.

**Comment by ImranR98** [comment] 2024-01-20 04:52
https://github.com/ImranR98/Obtainium/releases/tag/v0.16.0-beta

**Comment by linsui** [comment] 2024-01-22 14:20
@ImranR98 Do you want reproducible build for the F-Droid build? I'm not sure if it's what you want. With reproducible build the apk signed by you will be published directly. I ask because [the PR for that](https://github.com/ImranR98/Obtainium/pull/253) was merged but the target branch is removed. For reproducible build we still need that to ensure the same flutter version is used. You can also declare the flutter version somewhere else though. Currently you always use the latest stable flutter version.

**Comment by licaon-kter** [comment] 2024-01-22 15:35
Since F-Droid needs to build `background_fetch` from source not sure we can hope for reproducibility

**Comment by ImranR98** [comment] 2024-01-22 16:14
> Do you want reproducible build for the F-Droid build?

The F-Droid inclusion issue has been pushed by other contributors from the start (I've only been merging PRs etc.) so I'm not sure. Sounds like reproducible builds may not be possible?

I'll remove the F-Droid APKs from future releases since it isn't clear whether they will actually be used or if F-Droid will be doing their own signed builds, and they are just causing confusion right now (people accidentally downloading them, causing App ID issues). Instead I can attach the builds to this issue.

**Comment by ImranR98** [comment] 2024-01-22 16:34
> I ask because https://github.com/ImranR98/Obtainium/pull/253 was merged but the target branch is removed.

Sorry, I must have deleted the branch thinking whatever it was for had already been merged to main. I can put the changes from that PR back onto main if someone indicates that would enable reproducible builds (not sure since @licaon-kter mentioned it might not be).

**Comment by ImranR98** [comment] 2024-01-22 17:36
I've merged the commit and updated the submodule to make sure it's on the commit for Flutter's latest stable branch. I've also updated the GitHub actions CI to crash if I ever forget to update the submodule (haven't confirmed it works yet).

**Comment by licaon-kter** [comment] 2024-01-29 09:39
Merged in F-Droid and reproducible? Congrats :tada:

**Comment by shuvashish76** [comment] 2024-02-03 11:57
Live on F-Droid : https://f-droid.org/packages/dev.imranr.obtainium.fdroid/
Feel free to use their badge: https://gitlab.com/fdroid/artwork/-/blob/master/badge/README.md

**Closed** 2024-02-03 20:47 UTC
Labels: enhancement
