### ISSUE TITLE
Apps Icon

### ISSUE THREAD

**Issue by persianGOD** [ImranR98/Obtainium#1154] opened 2023-12-14 10:57 UTC
Hi...Thanks for your great app...I think it can be better to add a feature to your app that allow us turn icon on or off for app which not installed. Because it's hard when you want to install them again and if their icon available there it would be easier to remember them and choose to install.

**Comment by ImranR98** [comment] 2023-12-15 11:48
Duplicate of #611 (see also #811 and #1109).

**Closed by ImranR98** 2023-12-15 11:48 UTC
Labels: enhancement, to check
