### ISSUE TITLE
Some app icons are not displayed

### ISSUE THREAD

**Issue by Chungaa** [ImranR98/Obtainium#1950] opened 2024-11-04 15:04 UTC
Some app icons are not displayed.
For example, if you add a Github repo and then click on apply, the icon symbol of the app is not displayed.

Here are a few examples:
https://github.com/bttv-android/bttv
https://github.com/fgl27/smarttv-twitch
https://github.com/Kunzisoft/KeePassDX/releases

**Comment by ImranR98** [comment] 2024-11-04 15:09
Is this before or after installing the app? If it's before then that's expected since icons are taken from the OS (for installed apps).

**Comment by ImranR98** [comment] 2024-11-08 18:24
Closing - expected behaviour (and there is an existing issue to change that).

**Closed by ImranR98** 2024-11-08 18:24 UTC
Labels: bug, to check
