### ISSUE TITLE
When using the update, it will automatically jump to the initial interface.

### ISSUE THREAD

**Issue by GTX2090ti** [ImranR98/Obtainium#662] opened 2023-07-14 13:47 UTC
After downloading to 100%, it will automatically jump back to the interface that was just opened. The mobile phone is k50 and MIUI14.

**Comment by ImranR98** [comment] 2023-07-15 00:19
This is by design - you go back to the apps list page after installing an app.

**Comment by GTX2090ti** [comment] 2023-07-15 00:48
> This is by design - you go back to the apps list page after installing an app.

It's not that the installation is completed, but that the download is completed and you jump back to the initial interface without skipping the installation.

**Comment by ImranR98** [comment] 2023-07-15 00:50
Could you post a recording. Not sure what you mean exactly

**Comment by GTX2090ti** [comment] 2023-07-15 08:43
> Could you post a recording. Not sure what you mean exactly

>[]()@https://github.com/ImranR98/Obtainium/assets/44355019/000cf037-6be6-4b1b-b66f-1bac47c20c91

**Comment by ImranR98** [comment] 2023-08-05 18:25
This is most likely a duplicate of #661 - same issue (no installer popup) on the same OS skin (MIUI).

**Closed by ImranR98** 2023-08-05 18:25 UTC
Labels: needs follow up
