### ISSUE TITLE
Obtainium should not check for new versions when there is no internet connection

### ISSUE THREAD

**Issue by cybgh7** [ImranR98/Obtainium#1677] opened 2024-06-17 17:16 UTC
It is very annoying that Obtainium continues to check for new versions of integrated software, even when there is no internet connection.

When disconnecting WiFi and mobile data in the evening, the next morning there are mulitple error messages displayed that there was an error checking for updates.

Obtainium should stop checking when there is no internet connection available.

**Comment by ImranR98** [comment] 2024-06-18 22:22
Duplicate of #1120

**Closed by ImranR98** 2024-06-18 22:22 UTC
Labels: bug, to check
