### ISSUE TITLE
Can't install anything with or without miui package installer

### ISSUE THREAD

**Issue by User1l0** [ImranR98/Obtainium#2037] opened 2024-12-14 11:23 UTC
Here's how the package manager called
com.miui.packageinstaller

Wanna say that i think miui package installer is not the problem, but the obtainiums inability to choose and set your package installer before installing and apk update from any source.

Reminder that all any other apps from Google play or manually installed are working fine and show install popup on the com.miui.packageinstaller

**Comment by ImranR98** [comment] 2024-12-24 13:39
Duplicate of #1321

**Closed by ImranR98** 2024-12-24 13:39 UTC
