### ISSUE TITLE
Some F-Droid apps can't be added

### ISSUE THREAD

**Issue by quartzparchmentshears** [ImranR98/Obtainium#575] opened 2023-05-17 21:38 UTC
_Device: moto 5g ace
OS: Android 11_

_What is expected:_ Try to add [mueller-ma's Coffee](https://f-droid.org/de/packages/com.github.muellerma.coffee/)  from F-Droid.
App should add to list

_What actually happens:_ Try to add above app, Obtainium gives error, app "Not found". Changing any of the F-Droid source settings makes no difference and Obtainium can't add it

I've also tried changing the domain suffix to en, or omitting it from the URL altogether but results in the same error. What is different to Coffee than any other app on F-Droid?

![Screenshot_20230517-153241-755](https://github.com/ImranR98/Obtainium/assets/133920292/c5043021-d181-4756-aae7-5debc6941895)

**Comment by ImranR98** [comment] 2023-05-17 22:47
Not an Obtaiunium issue

Duplicate of #528

**Closed by ImranR98** 2023-05-17 22:47 UTC

**Comment by quartzparchmentshears** [comment] 2023-05-18 00:19
My mistake. Obviously I had not searched thoroughly enough to see if this issue already exists. But, now I know its an issue with the F-Droid API.
