### ISSUE TITLE
Feature request - Support for zip download for Magisk / LSPosed modules

### ISSUE THREAD

**Issue by FlorentLM** [ImranR98/Obtainium#1010] opened 2023-10-15 13:04 UTC
Many Magisk and LSPosed modules are only distributed through GitHub and are not in the repos (especially true for Magisk modules since the official app does not have any repo anymore and the only alternative is now awful) so it would be cool to be able to add these to Obtainium.

Being able to install directly would be a plus, but it's not crucial, could be just download the new zips to a specific folder.

Loving Obtainium by the way!

Thanks

**Comment by ImranR98** [comment] 2023-10-18 00:30
Duplicate of #983

**Closed by ImranR98** 2023-10-18 00:30 UTC
Labels: enhancement, to check
