### ISSUE TITLE
Cannot Download Release Asset

### ISSUE THREAD

**Issue by jm355** [ImranR98/Obtainium#1968] opened 2024-11-11 16:35 UTC
**Describe the bug**
Trying to update garmin explore from uptodown, it failed to install

**To Reproduce**
1. add https://garmin-explore.en.uptodown.com/android/download
2. update it (assuming you already had the app installed)

**Screenshots and Logs**
![Screenshot_20241111-092940](https://github.com/user-attachments/assets/dcd0385c-18af-4f3b-8e50-5ddfcdf1f594)![Screenshot_20241111-092949](https://github.com/user-attachments/assets/e70f256e-774c-4762-a560-5cfe1f0486d4)

**Please complete the following information:**
 - Device: Pixel 8
 - OS: GrapheneOS
 - Obtainium Version: 1.1.30

**Additional context**
i didn't realize uptodown had an english site till recently, and obtainium doesn't work with the spanish version of the url. Might be worth automatically converting the url, or at least confirming with the user. I think the only difference is adding ".en" and replacing "descargar" with "download"

**Comment by jm355** [comment] 2024-11-11 16:39
Same issue with https://connect-iq-store.en.uptodown.com/android/download and https://lovense-remote.en.uptodown.com/android/download

**Comment by jm355** [comment] 2024-11-13 17:22
https://connect.en.uptodown.com/android/download also has this issue now that an update is available

**Comment by DarkCrypt** [comment] 2024-11-13 19:58
More than likely a duplicate as stated. Every posted link leads to an xapk.

**Comment by jm355** [comment] 2024-11-14 02:50
When I attempt to download the release asset, I get this error 
![Screenshot_20241113-194916](https://github.com/user-attachments/assets/83936f1d-d6b3-4cf7-b1ce-e7c758d96943) ![Screenshot_20241113-194829](https://github.com/user-attachments/assets/d4a65660-150e-40fd-b699-df9dc4423070)

**Comment by ImranR98** [comment] 2024-11-15 02:25
Yes, the install failure is definitely a duplicate of #682 but the "download release asset" issue is a separate bug that will be fixed in the next release.

**Closed** 2024-11-15 17:56 UTC
Labels: bug, TODO
