### ISSUE TITLE
Improve Download Mechanisms and Import Options

### ISSUE THREAD

**Issue by obakha** [ImranR98/Obtainium#2020] opened 2024-12-09 21:42 UTC
**Prerequisites**

**Describe the feature**
This feature request addresses two key areas for improvement in Obtainium: enhancing download efficiency and offering more flexibility for importing apps from GitHub.

**Additional context**
#### Part 1: Enhance Download Speed and Flexibility  
Referencing issue [#580 - Accelerate download](https://github.com/Obtainium/Obtainium/issues/580), I propose improving download efficiency by:  
1. **Allowing simultaneous downloads** to queue or download multiple apps concurrently, reducing inefficiency.  
2. **Supporting multi-threaded downloads** (e.g., via [aria2](https://aria2.github.io/) or [navi](https://github.com/denisidoro/navi)) or enabling external downloaders to address slow single-thread downloads (<100 kBps).

#### Part 2: Import GitHub Starred Repos by List  
Currently, importing/exporting apps relies on importing all starred repositories, which can be cumbersome. It would be immensely helpful if Obtainium allowed users to import apps from specific lists on a GitHub profile. For instance:  
- I maintain a GitHub list titled _"Tested & Trusted FOSS Apps,"_ which contains all the apps I have vetted and actively use.  
- Adding an option to choose from such lists would make it easier to curate and manage imported apps.

**Comment by ImranR98** [comment] 2024-12-09 22:34
Duplicate of #580 (as mentioned) and #759.

**Closed by ImranR98** 2024-12-09 22:34 UTC
Labels: enhancement, to check
