### ISSUE TITLE
Version Modification (Bug and Feature Request)

### ISSUE THREAD

**Issue by NicholasFlamy** [ImranR98/Obtainium#1235] opened 2024-01-02 16:52 UTC
**Prerequisites**
Done
Done
**Describe the feature**
So we have Version extraction RegEx for HTML, but the app I'm working with has dashes on the apk link rather than dots. Since the Match group only allows a single integer I don't know what I can do. Maybe if there was a version modification RegEx then that would be helpful. Right now I have `minecraft\-pe\/(.*?)\/minecraft` with Match Group as `1` but if I could modify the output and RegEx replace the dashes with dots that would work.

For new Sources, it's preferable (not required) if you suggest how the following details can be extracted from the Source in a reliable way (like an API or through web scraping):
- The App version (or any release-specific identifier - a "pseudo-version") for the latest release
- One or more APK URL(s) for the latest release
- Above details for previous releases (optional)

Note that the Web scraper cannot deal with JavaScript-enabled content. -->

**Describe alternatives you've considered (if applicable)**
The Match Group could have RegEx. So I would set the Version Extraction RegEx to `minecraft\-pe\/((\d+)-(\d+)-(\d+)-(\d+))\/minecraft` and have `$1.$2.$3.$4` (maybe the dots need to be escaped: `$1\.$2\.$3\.$4`. Maybe the Match Groups could just have a standard setup that allows entering multiple groups with a standard separator (up to you, but something like a dot or a comma) so that people could just make groups in the Version Extraction RegEx and then add them to the Match Group so that it would be easy to work with any versioning. 

Note that app-specific Sources are less likely to be added. In those cases, see if the HTML Source will work for you (if not, see if a generally-applicable enhancement to the HTML Source would work, and suggest that instead). -->

**Additional context**
What I have now:
![Screenshot_20240102_104742](https://github.com/ImranR98/Obtainium/assets/30300649/9f9f9cf5-dc4b-48c5-a6cf-fb6b035e361f)
![Screenshot_20240102_105104](https://github.com/ImranR98/Obtainium/assets/30300649/620380fe-f3c5-4749-9918-71ef337ad6f0)

**Comment by NicholasFlamy** [comment] 2024-01-02 16:53
What I described as the alternative is probably the best.

**Comment by NicholasFlamy** [comment] 2024-01-02 16:53
Also, shout out to regex101.com because I'm doing this on mobile and it's a helpful tool for testing RegEx.

**Comment by NicholasFlamy** [comment] 2024-01-02 16:58
This is kind of a bug too because the app shows that it needs an update if I hit reset install status even though the versions show up identical with the exception of the dashes vs the dots.

**Comment by NicholasFlamy** [comment] 2024-01-02 17:42
Another app I'm using is modded and it reports that base app version number in Android but the download link for the apk only has the mod version. They have the base version listed on their page and I was able to use the options in the screenshots to make it work perfectly because the site has dots in the version.

![Screenshot_20240102_123840_Chrome](https://github.com/ImranR98/Obtainium/assets/30300649/37e1d44e-e066-4d27-8028-6624c7b45de3)
![Screenshot_20240102_124009](https://github.com/ImranR98/Obtainium/assets/30300649/b1be416f-ac06-41dd-a4b7-231a24698f4d)
![Screenshot_20240102_124026](https://github.com/ImranR98/Obtainium/assets/30300649/c6db5584-1ee0-4cd3-a9b7-8fcf2ce974e1)

**Comment by NicholasFlamy** [comment] 2024-01-02 17:44
> Another app I'm using is modded and it reports that base app version number in Android but the download link for the apk only has the mod version. They have the base version listed on their page and I was able to use the options in the screenshots to make it work perfectly because the site has dots in the version.
> 
> ![Screenshot_20240102_123840_Chrome](https://private-user-images.githubusercontent.com/30300649/293751485-37e1d44e-e066-4d27-8028-6624c7b45de3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTc2NDQsIm5iZiI6MTcwNDIxNzM0NCwicGF0aCI6Ii8zMDMwMDY0OS8yOTM3NTE0ODUtMzdlMWQ0NGUtZTA2Ni00ZDI3LTgwMjgtNjYyNGM3YjQ1ZGUzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDE3NDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhYzFjN2UyNDhlYzEwYTQ5NGE2NTdlZTk3ZjQyZTEyMTFlNjQ3NGE1MmEzNTEzYjA4MjE1N2UwOWRjMjcwMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xLKngm7PXGdKDEC3IDlEWA4oPg6UaT3NJ36E1vLf43E) ![Screenshot_20240102_124009](https://private-user-images.githubusercontent.com/30300649/293751486-b1be416f-ac06-41dd-a4b7-231a24698f4d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTc2NDQsIm5iZiI6MTcwNDIxNzM0NCwicGF0aCI6Ii8zMDMwMDY0OS8yOTM3NTE0ODYtYjFiZTQxNmYtYWMwNi00MWRkLWE0YjctMjMxYTI0Njk4ZjRkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDE3NDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhZTdjOTlmYmQ3ODcxODdmODUxMjFiMDgzYjRlNmM0ZjU3MTFjMDUwZjU4MzUwMDkzYTdiM2ZhNzJjZjY4ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qQxcBWekUEmdGzT1frmZSYpLqRGG9umjXLKkz5GqJnI) ![Screenshot_20240102_124026](https://private-user-images.githubusercontent.com/30300649/293751489-c6db5584-1ee0-4cd3-a9b7-8fcf2ce974e1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTc2NDQsIm5iZiI6MTcwNDIxNzM0NCwicGF0aCI6Ii8zMDMwMDY0OS8yOTM3NTE0ODktYzZkYjU1ODQtMWVlMC00Y2QzLWE5YjctOGZjZjJjZTk3NGUxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDE3NDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMDU4ZWZjY2ExZWNhMGJmNGQzMWI0N2Q5NDdhZGZkOGNhZTIxZmVmNjA1ZTk1M2QwMjI1MTgwZGI3ZDA0NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jIl31CEtDIQorVrqitQCx9K0FDu6mO6dsyxZYeCQ_9U)

Now this app also gives cleartext errors anytime I click on the app in Obtainium and makes it impossible to edit the details so I have to delete and re-add to Obtainium every time but that fine because otherwise it's perfect. I might post a separate issue. 
![Screenshot_20240102_124052](https://github.com/ImranR98/Obtainium/assets/30300649/230c4b75-fd26-4222-b009-219b0d59de32)
![Screenshot_20240102_124043](https://github.com/ImranR98/Obtainium/assets/30300649/efe32b5e-e874-46b9-bfc1-f6e2e0950f1a)

**Comment by NicholasFlamy** [comment] 2024-01-02 17:50
I'll add to this, the app that I originally was talking about which has the problem is Minecraft on apkvision and I know they have the version listed with dots on the page, but unlike the app that works perfectly, apkvision lists older versions as well as Beta versions so I'm hoping that it doesn't get screwed up by that. I do have Intermediate link as `^Download\ APK\ v(?!.*Beta|.*Preview|.*Mod).*$` so that it will get the normal version and I guess I could try combining this with what I have for the app that works perfectly but this seems janky.

**Comment by NicholasFlamy** [comment] 2024-01-02 20:41
> I'll add to this, the app that I originally was talking about which has the problem is Minecraft on apkvision and I know they have the version listed with dots on the page, but unlike the app that works perfectly, apkvision lists older versions as well as Beta versions so I'm hoping that it doesn't get screwed up by that. I do have Intermediate link as `^Download\ APK\ v(?!.*Beta|.*Preview|.*Mod).*$` so that it will get the normal version and I guess I could try combining this with what I have for the app that works perfectly but this seems janky.

Doesn't work because I need an intermediate link and that page does not have the version so I can't do that. Maybe the version extraction could let you choose what page?

**Comment by NicholasFlamy** [comment] 2024-01-02 20:46
Also, I think Obtainium believes that 1.20.50.03 is newer than 1.20.51.01

**Comment by ImranR98** [comment] 2024-01-04 01:10
> **Describe alternatives you've considered (if applicable)**
> The Match Group could have RegEx.

This is the solution I've implemented (note that it's not right to call it a "regex" since it's a custom pattern). So you'll be able to set the 'match group' field to `$1.$2.$3.$4` with the version extraction regex set to `(\d+)-(\d+)-(\d+)-(\d+)`.

> This is kind of a bug too because the app shows that it needs an update if I hit reset install status even though the versions show up identical with the exception of the dashes vs the dots.

Not a bug. The whole point of version detection is to avoid having to manually correct mistakes in the version shown by Obtainium. When version detection is disabled, you are given extra buttons to manually help correct errors. Don't press 'reset install status' if you don't need to. 

> Also, I think Obtainium believes that 1.20.50.03 is newer than 1.20.51.01

Not a bug. As long as the versions are different, Obtainium assumes it's an update. This is because versions are not always numerical - they could be strings or some numerical system that isn't "bigger = newer". This way is more flexible.

> this app also gives cleartext errors

What URL is causing that?

**Comment by ImranR98** [comment] 2024-01-04 01:10
Actually, create a new issue for the cleartext thing.

**Comment by ImranR98** [comment] 2024-01-04 01:12
Nvm, the cleartext bug will also be fixed in the next release: https://github.com/flutter/flutter/issues/30368

**Comment by NicholasFlamy** [comment] 2024-01-04 01:16
> This is the solution I've implemented (note that it's not right to call it a "regex" since it's a custom pattern). So you'll be able to set the 'match group' field to `$1.$2.$3.$4` with the version extraction regex set to `(\d+)-(\d+)-(\d+)-(\d+)`.

If you mean that it's already implemented, I would like to add that the Match Group field forces a Numpad keyboard.

**Comment by ImranR98** [comment] 2024-01-04 01:18
Good catch. I would have forgotten to change that.

**Comment by NicholasFlamy** [comment] 2024-01-04 01:29
I'm not sure if this is a bug so I'm posting the question. Is it intended that when doing Version Extraction RegEx, it applies to the last intermediate link page? If this is intended, I'll PR the Wiki and add this. Sometimes the original page has useful version info the intermediate does not. Maybe if we could specify a link for the Version Extraction RegEx to apply to, then that could be useful. (For example, I could apply it to the Minecraft Bedrock Release Changelogs, which are separate from the Beat changelogs. This could add complications like it not matching the version, but that's for the user, like me, to figure out. If I could specify the link to the original page then there wouldn't be any problems and if I could specify any other page that's not your problem. Also, specifying any page could be a hidden setting that's enabled in the Obtainium settings if you're worried people will bug you about it. Also, I can help a little with the documentation for everything (there's a lot that I would like to add), but I'll work on it after I'm more confident in my ability to use Obtainium.)

**Comment by ImranR98** [comment] 2024-01-04 01:35
> the last intermediate link page

It is meant to apply to the final APK link, not any intermediate/"middle" ones. Are you seeing different behaviour?

We could always add a "Use for Version Extraction" toggle to each intermediate link. That way the user could indicate which link to use for version detection. If all intermediate links have that toggle disabled, we would stick to current behaviour. If multiple ones have it enabled, we would pick the last one which is able to successfully extract something.

> Also, I can help a little with the documentation for everything

Sure, PRs are welcome!

**Comment by ImranR98** [comment] 2024-01-04 01:37
https://github.com/ImranR98/Obtainium/releases/tag/v0.15.4-beta

**Comment by NicholasFlamy** [comment] 2024-01-04 01:37
> It is meant to apply to the final APK link, not any intermediate/"middle" ones. Are you seeing different behaviour?

I meant with the "Apply Version Extraction Regex to Entire Page" toggle enabled.

**Closed by ImranR98** 2024-01-04 01:37 UTC
Labels: enhancement, TODO

**Comment by ImranR98** [comment] 2024-01-04 01:41
In that case it should still apply to the final page on which the APK link is found.  So if you're using in an intermediate link, the regex would apply not to the final intermediate link itself, but to the content of the final intermediate link page (which contains the actual returned APK link). Hope that makes sense.

**Comment by NicholasFlamy** [comment] 2024-01-04 01:44
> In that case it should still apply to the final page on which the APK link is found. So if you're using an intermediate link, the regex would apply not to the final intermediate link itself, but to the content of the final intermediate link page (which contains the actual returned APK link). Hope that makes sense.

Yes, that makes sense and that is the behavior I discovered. I was suggesting any link to any page to use for the RegEx because there are cases where the apk is found on an intermediate page that doesn't contain the version. I won't have an immediate use case for this at the moment (thanks to the new implementation of Match Group), but it could come in handy.
