### ISSUE TITLE
Jittering progress bar and download progress percent

### ISSUE THREAD

**Issue by brendanfattig** [ImranR98/Obtainium#327] opened 2023-02-24 18:43 UTC
Obtainium version: 0.11.2
Android version: 13
Device: Pixel 6a

Just installed Obtainium on a recently reset Pixel 6a. Attempting to download an app from github.com that was discovered with the in-app search. The progress bar jitters around (while also increasing toward 100%). This is also represented in the app list showing the "Progress 25%" number also moving up and down ~5 times per second.

**Comment by brendanfattig** [comment] 2023-02-24 18:52
Can't replicate with successive app downloads :(

**Comment by ImranR98** [comment] 2023-02-24 23:25
Hmm, not sure what could've caused this (maybe the same App downloaded twice in parallel by mistake?) cause I can't replicate it either. What App was it?

**Comment by ImranR98** [comment] 2023-02-25 04:15
Closing this; will reopen if needed.

**Comment by brendanfattig** [comment] 2023-03-01 20:18
The app was SimpleX. I reset the phone again, installed Obtainium, then searched for SimpleX through Obtainium and had the same behavior. All apps installed after didn't have the same jiggling behavior.

**Comment by ImranR98** [comment] 2023-03-01 20:20
Is this the url? https://github.com/simplex-chat/simplex-chat/releases

Also did you use the default options or did you change anything?

**Comment by brendanfattig** [comment] 2023-03-02 05:59
Yeah, that's the URL. And yes, the default settings. I tried again with the latest version, 0.11.6, and had some varying results.

**Comment by ImranR98** [comment] 2023-03-17 20:48
I think this is due to tapping the button more than once (before it gets greyed out) as described in #361. Will be fixed in the next release.

**Comment by ImranR98** [comment] 2023-03-18 03:18
Assuming I'm right about the cause, it should be fixed now. Let me know to reopen the issue if it happens again: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.9-beta

**Closed by ImranR98** 2023-03-18 03:18 UTC
Labels: bug, needs follow up
