### ISSUE TITLE
Support for displaying exponents

### ISSUE THREAD

**Issue by iDazai** [ImranR98/Obtainium#1009] opened 2023-10-15 12:42 UTC
**Describe the bug**
Exponents aren't shown if there's an app with an exponent in its name, e.g. DAVx⁵
https://github.com/bitfireAT/davx5-ose

**To Reproduce**
1. Add Davx5 in Obtainium
2. "No Glyph" get shown in App name

**Screenshots and Logs**
![Screenshot_20231013-160521](https://github.com/ImranR98/Obtainium/assets/50296346/0c982c9e-5176-474c-924d-47fd64cc847f)

**Please complete the following information:**
 - Device: Pixel 5
 - OS: e.g. GrapheneOS
 - Obtainium 0.14.30-beta

**Comment by ImranR98** [comment] 2023-10-18 00:26
Duplicate of #170

**Closed by ImranR98** 2023-10-18 00:26 UTC
Labels: bug, to check
