### ISSUE TITLE
The application crashes abnormally

### ISSUE THREAD

**Issue by phucvn2002vn** [ImranR98/Obtainium#1223] opened 2023-12-31 03:42 UTC
**Prerequisites**
Only crashes when choosing to install using shizuku

**Describe the bug**
The application crashes when installing using shizuku

**To Reproduce**
1. Go to Settings
2. Tap on shizuku on InstallMethod
3. Go back and install an app
4. The application will crash

**Screenshots and Logs**
[crash-dev-imranr-obtainium-31_12-09-56-13_441.zip](https://github.com/ImranR98/Obtainium/files/13800116/crash-dev-imranr-obtainium-31_12-09-56-13_441.zip)

**Please complete the following information:**
 - Device: Google Pixel 3a XL
 - OS: Android 12
 - Obtainium Version: 0.15.2 beta

**Additional context**
No

**Comment by ImranR98** [comment] 2023-12-31 21:07
Hmm, the issue description looks like #1200 but the logs look more like #1221. Could you try the suggestion here: https://github.com/ImranR98/Obtainium/issues/1221#issuecomment-1873037159

I'm closing this unless it's confirmed to be different from those two.

**Closed by ImranR98** 2023-12-31 21:07 UTC
Labels: bug, to check
