### ISSUE TITLE
Option to show/hide personal access tokens (for both GitHub and GitLab)

### ISSUE THREAD

**Issue by maroeldawwyp** [ImranR98/Obtainium#1890] opened 2024-10-08 05:51 UTC
**Prerequisites**

**Describe the feature**

**Describe alternatives you've considered (if applicable)**

**Additional context**

**Comment by ImranR98** [comment] 2024-10-10 17:03
Duplicate of #694

**Closed by ImranR98** 2024-10-10 17:03 UTC
Labels: enhancement, to check
