### ISSUE TITLE
Support Search for Third-Party GitLab Instances and F-Droid Repos

### ISSUE THREAD

**Issue by cvoges12** [ImranR98/Obtainium#1108] opened 2023-11-22 16:44 UTC
### Problem ###

The search tool and such supports a broad spectrum of sources which can be used to obtain applications from. But many sources are still missing. Custom URLs to download APKs pop up all the time. And third-party F-Droid repositories are created all the time. It would be difficult to keep up with all of these. And I think Obtainium shouldn't endorse all sources / repositories.

### Description ###

Either in settings or somewhere else, there could be a way to add in custom sources and repositories. For custom third-party F-Droid repositories, only the URL and fingerprint are needed for a user to put in. Another thought is for custom git servers such as individual GitLab instances and such to be added as sources from within the app.

### Alternatives ###

- You could manually file an issue to add a source each time. But Obtainium probably shouldn't endorse every app source under the sun. And it isn't very user friendly to have a user come make an issue, convince the obtainium project why it should be added, wait for someone to add it, and wait for a new release of obtainium.
- You could say no to these other sources altogether. But then users will rely on competing projects such as F-Droid to accomplish the same behavior.

**Comment by LeOS-GSI** [comment] 2023-11-23 17:49
![Screenshot_20231123-184550_Trebuchet](https://github.com/ImranR98/Obtainium/assets/2726574/f54d261f-ba92-433f-802a-eba889dc40ab)

When adding my own Git I'm getting the above error

**Comment by LeOS-GSI** [comment] 2023-11-23 17:54
My f-droid repo is not found. I have used
http://192.168.1.96:3000/JoJo/apps/src/branch/master/fdroid/repo
and
http://192.168.1.96:3000/JoJo/apps/fdroid/repo

None is working

**Comment by ImranR98** [comment] 2023-11-23 18:04
@LeOS-GSI there is no way for Obtainium to guess what kind of source your website is (F-droid, gitlab, etc.) - you need to manually pick from the source override dropdown. Besides, your problem is not related to this issue.

**Comment by ImranR98** [comment] 2023-11-23 18:05
Duplicate of #582

**Comment by LeOS-GSI** [comment] 2023-11-23 18:32
> @LeOS-GSI there is no way for Obtainium to guess what kind of source your website is (F-droid, gitlab, etc.) - you need to manually pick from the source override dropdown. Besides, your problem is not related to this issue.

But there is no drop down :((

**Comment by LeOS-GSI** [comment] 2023-11-23 18:34
> Duplicate of #582

582 is different

**Comment by ImranR98** [comment] 2023-11-23 19:04
> 582 is different

It's not clear what you're asking - you can already add apps from third party repos. You also mentioned search but I don't see how search could work for the HTML source.

**Comment by ImranR98** [comment] 2023-11-23 19:06
Same for custom gitlab instances. You just need to select gitlab in the override dropdown.

**Comment by cvoges12** [comment] 2023-11-24 17:53
@ImranR98 This is not a duplicate. This has nothing to do with custom runtime scripts.

**Comment by cvoges12** [comment] 2023-11-24 18:04
> > 582 is different
> 
> It's not clear what you're asking - you can already add apps from third party repos. You also mentioned search but I don't see how search could work for the HTML source.

Excuse me. But I am not the same person as @LeOS-GSI so don't refer to him as the issue author. I don't know this guy, and he is rambling about something totally unrelated to this described issue.

Second, this has nothing to do with searching apps on existing third party F-Droid repositories. How F-Droid repositories work is that anyone can make an F-Droid repository. You're assuming that every single third party F-Droid repository can be searched. This is just untrue. There needs to be a way for users to add in their own F-Droid repositories.

Third, you're assuming there is only one GitLab instance. Unlike GitHub, where the platform is the only instance of the software, anyone can create a GitLab instance. There are in fact **many** GitLab instances out there. And there needs to be a feature to be able to add more.

**Comment by cvoges12** [comment] 2023-11-24 18:08
If you're still confused on what I'm referring to, please take a look at how F-Droid can add custom repositories from within the F-Droid app. They have a nice example of this feature.

**Comment by cvoges12** [comment] 2023-11-24 18:09
If anything, this feature being implemented would close #582 if this would be chosen instead.

**Comment by ImranR98** [comment] 2023-11-24 18:43
I don't think you understand what Obtainium currently supports. You are already able to add apps from custom third party f-droid repos and you can also do the same for custom third party GitLab instances. You do this by entering the URL of the app that you want, and then telling Obtanium what kind of source it is by selecting the relevant option from the source override dropdown.

Even after you have already added an app from your custom repo, in order to add another one you would once again have to use the source override menu. So it is different from the normal flow in that sense.

It's true that search doesn't currently work for third-party instances. Is that what you're asking to be added?

**Comment by ImranR98** [comment] 2023-11-24 18:43
Issue #582 is about adding entirely new kinds of sources, not F-Droid and not GitLab, but completely custom sites that people may want to use Obtainium with. That's what I thought you were talking about because third-party F-Droid repos and GitLab instances are already supported.

**Comment by cvoges12** [comment] 2023-11-24 21:05
> You are already able to add apps from custom third party f-droid repos and you can also do the same for custom third party GitLab instances

@ImranR98 No, I understand perfectly fine. I'm not talking about for adding. I'm talking about for **searching**. You do not have the ability to search for apps on third party F-Droid repos other than the ones hard coded into Obtainium. And no, you do not have the ability to search for apps on other GitLab instances.

**Comment by cvoges12** [comment] 2023-11-24 21:07
> Issue #582 is about adding entirely new kinds of sources, not F-Droid and not GitLab, but completely custom sites that people may want to use Obtainium with. That's what I thought you were talking about because third-party F-Droid repos and GitLab instances are already supported.

@ImranR98 Okay. Well, regardless that's way outside of the scope of this issue. You already have implemented these types of sources. So it is irrelevant and doesn't close this issue.

**Comment by ImranR98** [comment] 2023-11-24 21:09
That clarifies things. This is specifically about search.

**Comment by ImranR98** [comment] 2023-11-25 01:38
Added: https://github.com/ImranR98/Obtainium/releases/tag/v0.14.35-beta

Couldn't find a convenient way of adding it to the main search bar, so it's been added to the import/export page under 'Search Sources'

**Closed by ImranR98** 2023-11-25 01:38 UTC
Labels: enhancement, TODO

**Comment by cvoges12** [comment] 2023-11-28 16:26
@ImranR98 I think it would be better to add them persistently. Now one has to memorize the URL they search for applications instead of having it being added as a part of the third-party repositories. F-Droid solved this by putting `repositories` option in the settings menu. And you can add and remove them there.

**Comment by ImranR98** [comment] 2023-11-28 16:30
I think that would add unnecessary complexity for a niche use case. Instead how about being able to pick from a list of urls currently in use? If you have at least one app from a particular repo, for example, it would show up on a list in the search menu to pick again (if you remove all apps from that repo, it won't be on the list anymore).
