### ISSUE TITLE
root install fail 

### ISSUE THREAD

**Issue by KUKARAF** [ImranR98/Obtainium#1396] opened 2024-02-14 12:48 UTC
**Prerequisites**

**Describe the bug**

root install method causes all installs to fail 

**To Reproduce**
1. install  v1.0.2
2. change install method to root
3. cry because install fails with only info available being `error: invalid [app]`

**Screenshots and Logs**

**Please complete the following information:**
 - Device: note 9; crownlte; SM-N960F
 - OS: crdroid 9.13
 - Obtainium Version: 1.0.2 (2523)

**Additional context**

**Comment by pbanj** [comment] 2024-02-15 08:44
That explains a lot. Thought i was going crazy

**Comment by ImranR98** [comment] 2024-02-15 22:18
Closing as a duplicate of #1200. Root install may end up being removed (see https://github.com/ImranR98/Obtainium/issues/1200#issuecomment-1922511891)

**Closed by ImranR98** 2024-02-15 22:18 UTC
Labels: bug, to check
