### ISSUE TITLE
Can't download or update anything

### ISSUE THREAD

**Issue by sxarthur** [ImranR98/Obtainium#1520] opened 2024-04-05 17:50 UTC
**Describe the bug**
Any App added fails to download/update with no description Error
with Github and Fdroid

[Some Errors Occured]
%app%

**To Reproduce**
add an app
try to download/ update
error

**Screenshots and Logs**
2024-04-05 06:50:20.541: info: This is the first ever run of Obtainium.

2024-04-05 06:52:10.815: error: rate limit exceeded

2024-04-05 06:52:16.506: error: Too many requests (rate limited) - try again in 29 minutes

2024-04-05 14:37:17.058: error:  [com.github.libretube]

2024-04-05 14:42:16.961: error:  [com.github.libretube]

2024-04-05 14:43:01.710: error:  [org.fossify.filemanager] 

**Please complete the following information:**
 - Device: POCO F1
 - OS:  miui based on android 10
 - Obtainium Version: 1.1.0

**Comment by ImranR98** [comment] 2024-04-07 03:25
Duplicate of #1321

**Closed by ImranR98** 2024-04-07 03:25 UTC
Labels: bug, to check

**Comment by RaviThakurRajput** [comment] 2025-03-28 07:14
Hey anyone I ve installed hyper os china in my indian poco x6 without unlocking the bootloader and now i cant install any app and bootloader is.also not unlock its showint some.error.and apps.also not.installing its showing error -9477 or -999 and when i off.the.system optimization still isnt installing apps it just says app is no installed what to do
